// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delivery.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminAttemptOwner = `-- name: AdminAttemptOwner :one
SELECT m.actor,m.id FROM core.admin_message_deliveries d JOIN core.admin_messages m ON m.id=d.message_id
WHERE d.id=$1::bigint AND d.bot_id=$2::bigint AND d.attempt=$3::bigint
 AND (d.state IN ('pending','sending','unknown') OR (d.state='cancelled' AND d.failure='source_revoked'))
`

type AdminAttemptOwnerParams struct {
	ID      int64
	BotID   int64
	Attempt int64
}

type AdminAttemptOwnerRow struct {
	Actor string
	ID    int64
}

func (q *Queries) AdminAttemptOwner(ctx context.Context, arg AdminAttemptOwnerParams) (AdminAttemptOwnerRow, error) {
	row := q.db.QueryRow(ctx, adminAttemptOwner, arg.ID, arg.BotID, arg.Attempt)
	var i AdminAttemptOwnerRow
	err := row.Scan(&i.Actor, &i.ID)
	return i, err
}

const beginAdminSend = `-- name: BeginAdminSend :execrows
UPDATE core.admin_message_deliveries SET state='sending',lease_until=clock_timestamp()+interval '2 minutes',
 uncertain_resends=uncertain_resends+CASE WHEN last_uncertain_attempt IS NOT NULL THEN 1 ELSE 0 END
WHERE id=$1::bigint AND bot_id=$2::bigint AND attempt=$3::bigint
 AND state='pending' AND lease_until>clock_timestamp()
 AND (last_uncertain_attempt IS NULL OR uncertain_resends<3)
`

type BeginAdminSendParams struct {
	ID      int64
	BotID   int64
	Attempt int64
}

func (q *Queries) BeginAdminSend(ctx context.Context, arg BeginAdminSendParams) (int64, error) {
	result, err := q.db.Exec(ctx, beginAdminSend, arg.ID, arg.BotID, arg.Attempt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cancelUnauthorizedAdminPending = `-- name: CancelUnauthorizedAdminPending :exec
UPDATE core.admin_message_deliveries d SET state='cancelled',failure='publication_cancelled'
FROM core.admin_messages m WHERE m.id=d.message_id AND d.bot_id=$1::bigint
 AND d.state='pending' AND (m.state='cancelled'
 OR NOT EXISTS(SELECT 1 FROM core.pass_booking_admins a WHERE a.owner=m.actor))
`

func (q *Queries) CancelUnauthorizedAdminPending(ctx context.Context, botID int64) error {
	_, err := q.db.Exec(ctx, cancelUnauthorizedAdminPending, botID)
	return err
}

const enqueueAdminDeliveries = `-- name: EnqueueAdminDeliveries :exec
INSERT INTO core.admin_message_deliveries(message_id,destination,content,bot_id)
SELECT message_id,destination,content,CASE WHEN $1::bigint>0 THEN $1::bigint END
FROM core.admin_message_recipients WHERE message_id=$2::bigint ON CONFLICT DO NOTHING
`

type EnqueueAdminDeliveriesParams struct {
	BotID     int64
	MessageID int64
}

func (q *Queries) EnqueueAdminDeliveries(ctx context.Context, arg EnqueueAdminDeliveriesParams) error {
	_, err := q.db.Exec(ctx, enqueueAdminDeliveries, arg.BotID, arg.MessageID)
	return err
}

const expireAdminSends = `-- name: ExpireAdminSends :exec
UPDATE core.admin_message_deliveries SET state='unknown',failure='telegram_outcome_unknown'
WHERE bot_id=$1::bigint AND state='sending' AND lease_until<=clock_timestamp()
`

func (q *Queries) ExpireAdminSends(ctx context.Context, botID int64) error {
	_, err := q.db.Exec(ctx, expireAdminSends, botID)
	return err
}

const finishAdminDelivery = `-- name: FinishAdminDelivery :execrows
UPDATE core.admin_message_deliveries SET state=$1::text,
 telegram_message_id=$2::bigint,failure=$3::text,
 available_at=$4::timestamptz,lease_until=NULL,
 failure_count=failure_count+$5::bigint
WHERE id=$6::bigint AND bot_id=$7::bigint AND attempt=$8::bigint
 AND (state IN ('pending','sending','unknown') OR (state='cancelled' AND failure='source_revoked'))
`

type FinishAdminDeliveryParams struct {
	State            string
	MessageID        int64
	Failure          string
	AvailableAt      pgtype.Timestamptz
	FailureIncrement int64
	ID               int64
	BotID            int64
	Attempt          int64
}

func (q *Queries) FinishAdminDelivery(ctx context.Context, arg FinishAdminDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishAdminDelivery,
		arg.State,
		arg.MessageID,
		arg.Failure,
		arg.AvailableAt,
		arg.FailureIncrement,
		arg.ID,
		arg.BotID,
		arg.Attempt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lockAdminAttempt = `-- name: LockAdminAttempt :one
SELECT d.destination,d.state,d.telegram_message_id,d.available_at,d.failure,
 d.last_uncertain_attempt,d.last_confirmed_attempt,d.uncertain_resends,d.lease_until,
 COALESCE(d.lease_until>clock_timestamp(),false)::boolean AS lease_live
FROM core.admin_message_deliveries d WHERE d.id=$1::bigint
 AND d.bot_id=$2::bigint AND d.attempt=$3::bigint
FOR UPDATE
`

type LockAdminAttemptParams struct {
	ID      int64
	BotID   int64
	Attempt int64
}

type LockAdminAttemptRow struct {
	Destination          []byte
	State                string
	TelegramMessageID    int64
	AvailableAt          pgtype.Timestamptz
	Failure              string
	LastUncertainAttempt pgtype.Int8
	LastConfirmedAttempt pgtype.Int8
	UncertainResends     int64
	LeaseUntil           pgtype.Timestamptz
	LeaseLive            bool
}

func (q *Queries) LockAdminAttempt(ctx context.Context, arg LockAdminAttemptParams) (LockAdminAttemptRow, error) {
	row := q.db.QueryRow(ctx, lockAdminAttempt, arg.ID, arg.BotID, arg.Attempt)
	var i LockAdminAttemptRow
	err := row.Scan(
		&i.Destination,
		&i.State,
		&i.TelegramMessageID,
		&i.AvailableAt,
		&i.Failure,
		&i.LastUncertainAttempt,
		&i.LastConfirmedAttempt,
		&i.UncertainResends,
		&i.LeaseUntil,
		&i.LeaseLive,
	)
	return i, err
}

const lockAdminDelivery = `-- name: LockAdminDelivery :one
SELECT d.id,d.message_id,d.destination,COALESCE(d.content,m.request->'content')::jsonb AS content,
 d.state,d.attempt,m.actor,u.telegram_id
FROM core.admin_message_deliveries d JOIN core.admin_messages m ON m.id=d.message_id
JOIN core.pass_booking_admins a ON a.owner=m.actor JOIN core.users u ON u.id=m.actor
WHERE d.id=$1::bigint AND d.bot_id=$2::bigint
 AND m.state='queued' AND d.state='pending' AND d.available_at<=clock_timestamp()
 AND (d.lease_until IS NULL OR d.lease_until<=clock_timestamp())
FOR UPDATE OF d,m SKIP LOCKED FOR SHARE OF a
`

type LockAdminDeliveryParams struct {
	ID    int64
	BotID int64
}

type LockAdminDeliveryRow struct {
	ID          int64
	MessageID   int64
	Destination []byte
	Content     []byte
	State       string
	Attempt     int64
	Actor       string
	TelegramID  int64
}

func (q *Queries) LockAdminDelivery(ctx context.Context, arg LockAdminDeliveryParams) (LockAdminDeliveryRow, error) {
	row := q.db.QueryRow(ctx, lockAdminDelivery, arg.ID, arg.BotID)
	var i LockAdminDeliveryRow
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.Destination,
		&i.Content,
		&i.State,
		&i.Attempt,
		&i.Actor,
		&i.TelegramID,
	)
	return i, err
}

const nextAdminDeliveries = `-- name: NextAdminDeliveries :many
SELECT d.id,d.message_id,m.actor FROM core.admin_message_deliveries d
JOIN core.admin_messages m ON m.id=d.message_id
JOIN core.pass_booking_admins a ON a.owner=m.actor
WHERE d.bot_id=$1::bigint AND m.state='queued' AND d.state='pending'
 AND d.available_at<=clock_timestamp() AND (d.lease_until IS NULL OR d.lease_until<=clock_timestamp())
 AND NOT EXISTS(SELECT 1 FROM core.admin_message_deliveries earlier
  WHERE (earlier.bot_id=d.bot_id OR earlier.bot_id IS NULL) AND earlier.destination->>'chat'=d.destination->>'chat'
   AND COALESCE(earlier.destination->>'thread','0')=COALESCE(d.destination->>'thread','0')
   AND earlier.id<d.id AND earlier.state IN ('pending','sending','unknown','parked','paused'))
ORDER BY d.id LIMIT 25
`

type NextAdminDeliveriesRow struct {
	ID        int64
	MessageID int64
	Actor     string
}

func (q *Queries) NextAdminDeliveries(ctx context.Context, botID int64) ([]NextAdminDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, nextAdminDeliveries, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NextAdminDeliveriesRow{}
	for rows.Next() {
		var i NextAdminDeliveriesRow
		if err := rows.Scan(&i.ID, &i.MessageID, &i.Actor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const prepareAdminDelivery = `-- name: PrepareAdminDelivery :one
UPDATE core.admin_message_deliveries SET attempt=attempt+1,lease_until=clock_timestamp()+interval '2 minutes'
WHERE id=$1::bigint RETURNING attempt
`

func (q *Queries) PrepareAdminDelivery(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, prepareAdminDelivery, id)
	var attempt int64
	err := row.Scan(&attempt)
	return attempt, err
}

const recordAdminConfirmation = `-- name: RecordAdminConfirmation :exec
UPDATE core.admin_message_deliveries SET last_confirmed_attempt=$1::bigint
WHERE id=$2::bigint AND bot_id=$3::bigint AND attempt=$1::bigint
`

type RecordAdminConfirmationParams struct {
	Attempt int64
	ID      int64
	BotID   int64
}

func (q *Queries) RecordAdminConfirmation(ctx context.Context, arg RecordAdminConfirmationParams) error {
	_, err := q.db.Exec(ctx, recordAdminConfirmation, arg.Attempt, arg.ID, arg.BotID)
	return err
}

const recordAdminTerminalConfirmation = `-- name: RecordAdminTerminalConfirmation :execrows
UPDATE core.admin_message_deliveries SET last_confirmed_attempt=$1::bigint
WHERE id=$2::bigint AND bot_id=$3::bigint
 AND attempt=$1::bigint AND last_uncertain_attempt=$1::bigint
 AND state IN ('failed','cancelled') AND lease_until IS NULL
`

type RecordAdminTerminalConfirmationParams struct {
	Attempt int64
	ID      int64
	BotID   int64
}

func (q *Queries) RecordAdminTerminalConfirmation(ctx context.Context, arg RecordAdminTerminalConfirmationParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordAdminTerminalConfirmation, arg.Attempt, arg.ID, arg.BotID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordAdminTerminalReceipt = `-- name: RecordAdminTerminalReceipt :execrows
UPDATE core.admin_message_deliveries SET telegram_message_id=$1::bigint
WHERE id=$2::bigint AND bot_id=$3::bigint
 AND attempt=$4::bigint AND last_uncertain_attempt=$4::bigint
 AND COALESCE(last_confirmed_attempt,0)<$4::bigint
 AND state IN ('failed','cancelled') AND lease_until IS NULL
 AND $1::bigint>0
 AND (telegram_message_id=0 OR telegram_message_id=$1::bigint)
`

type RecordAdminTerminalReceiptParams struct {
	MessageID int64
	ID        int64
	BotID     int64
	Attempt   int64
}

func (q *Queries) RecordAdminTerminalReceipt(ctx context.Context, arg RecordAdminTerminalReceiptParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordAdminTerminalReceipt,
		arg.MessageID,
		arg.ID,
		arg.BotID,
		arg.Attempt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordAdminUncertainty = `-- name: RecordAdminUncertainty :exec
UPDATE core.admin_message_deliveries SET last_uncertain_attempt=$1::bigint,
 last_uncertain_reason=$2::text,last_uncertain_recorded_at=clock_timestamp()
WHERE id=$3::bigint AND bot_id=$4::bigint AND attempt=$1::bigint
 AND (last_uncertain_attempt IS NULL OR last_uncertain_attempt<$1::bigint)
`

type RecordAdminUncertaintyParams struct {
	Attempt int64
	Reason  string
	ID      int64
	BotID   int64
}

func (q *Queries) RecordAdminUncertainty(ctx context.Context, arg RecordAdminUncertaintyParams) error {
	_, err := q.db.Exec(ctx, recordAdminUncertainty,
		arg.Attempt,
		arg.Reason,
		arg.ID,
		arg.BotID,
	)
	return err
}
