// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CoreDeliveryQueue struct {
	BotID        int64
	OwnerKind    string
	OwnerKey     string
	EffectKey    string
	Chat         string
	ThreadID     int64
	LaneSequence int64
	TrafficClass string
	State        string
	NotBefore    pgtype.Timestamptz
}
