// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pacing.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deliveryClock = `-- name: DeliveryClock :one
SELECT clock_timestamp()::timestamptz AS now
`

func (q *Queries) DeliveryClock(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, deliveryClock)
	var now pgtype.Timestamptz
	err := row.Scan(&now)
	return now, err
}

const ensurePacing = `-- name: EnsurePacing :exec
INSERT INTO core.delivery_pacing(bot_id,chat) VALUES($1::bigint,$2::text)
ON CONFLICT DO NOTHING
`

type EnsurePacingParams struct {
	BotID int64
	Chat  string
}

func (q *Queries) EnsurePacing(ctx context.Context, arg EnsurePacingParams) error {
	_, err := q.db.Exec(ctx, ensurePacing, arg.BotID, arg.Chat)
	return err
}

const extendPacing = `-- name: ExtendPacing :exec
UPDATE core.delivery_pacing SET not_before=GREATEST(not_before,$1::timestamptz),
 pause_reason=CASE WHEN $2::text<>'' THEN $2::text ELSE pause_reason END
WHERE bot_id=$3::bigint AND chat=$4::text
`

type ExtendPacingParams struct {
	NotBefore   pgtype.Timestamptz
	PauseReason string
	BotID       int64
	Chat        string
}

func (q *Queries) ExtendPacing(ctx context.Context, arg ExtendPacingParams) error {
	_, err := q.db.Exec(ctx, extendPacing,
		arg.NotBefore,
		arg.PauseReason,
		arg.BotID,
		arg.Chat,
	)
	return err
}

const lockPacing = `-- name: LockPacing :one
SELECT not_before,pause_reason FROM core.delivery_pacing
WHERE bot_id=$1::bigint AND chat=$2::text FOR UPDATE
`

type LockPacingParams struct {
	BotID int64
	Chat  string
}

type LockPacingRow struct {
	NotBefore   pgtype.Timestamptz
	PauseReason string
}

func (q *Queries) LockPacing(ctx context.Context, arg LockPacingParams) (LockPacingRow, error) {
	row := q.db.QueryRow(ctx, lockPacing, arg.BotID, arg.Chat)
	var i LockPacingRow
	err := row.Scan(&i.NotBefore, &i.PauseReason)
	return i, err
}
