// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queue.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceDeliveryFairness = `-- name: AdvanceDeliveryFairness :one
INSERT INTO core.delivery_fairness(bot_id,grants) VALUES($1::bigint,1)
ON CONFLICT(bot_id) DO UPDATE SET grants=core.delivery_fairness.grants+1 RETURNING grants
`

func (q *Queries) AdvanceDeliveryFairness(ctx context.Context, botID int64) (int64, error) {
	row := q.db.QueryRow(ctx, advanceDeliveryFairness, botID)
	var grants int64
	err := row.Scan(&grants)
	return grants, err
}

const allocateDeliverySequence = `-- name: AllocateDeliverySequence :one
UPDATE core.delivery_lanes SET next_sequence=next_sequence+1
WHERE bot_id=$1::bigint AND chat=$2::text RETURNING next_sequence
`

type AllocateDeliverySequenceParams struct {
	BotID int64
	Chat  string
}

func (q *Queries) AllocateDeliverySequence(ctx context.Context, arg AllocateDeliverySequenceParams) (int64, error) {
	row := q.db.QueryRow(ctx, allocateDeliverySequence, arg.BotID, arg.Chat)
	var next_sequence int64
	err := row.Scan(&next_sequence)
	return next_sequence, err
}

const deliveryCandidates = `-- name: DeliveryCandidates :many
WITH heads AS (
 SELECT DISTINCT ON (bot_id,chat) bot_id, owner_kind, owner_key, effect_key, chat, thread_id, lane_sequence, traffic_class, state, not_before FROM core.delivery_queue
 WHERE bot_id=$2::bigint AND state IN ('pending','sending','unknown','parked','paused')
 ORDER BY bot_id,chat,lane_sequence
)
SELECT h.bot_id, h.owner_kind, h.owner_key, h.effect_key, h.chat, h.thread_id, h.lane_sequence, h.traffic_class, h.state, h.not_before FROM heads h JOIN core.delivery_lanes l USING(bot_id,chat)
LEFT JOIN core.delivery_fairness f USING(bot_id)
LEFT JOIN core.delivery_pacing b ON b.bot_id=h.bot_id AND b.chat=''
LEFT JOIN core.delivery_pacing c ON c.bot_id=h.bot_id AND c.chat=h.chat
WHERE h.state='pending' AND h.not_before<=clock_timestamp()
AND COALESCE(b.pause_reason,'')='' AND COALESCE(c.pause_reason,'')=''
AND COALESCE(b.not_before,'-infinity'::timestamptz)<=clock_timestamp()
AND COALESCE(c.not_before,'-infinity'::timestamptz)<=clock_timestamp()
ORDER BY (h.traffic_class <> CASE WHEN COALESCE(f.grants,0)%4=3 THEN 'background' ELSE 'interactive' END),
 l.last_served,h.chat,h.lane_sequence
LIMIT $1::integer
`

type DeliveryCandidatesParams struct {
	Maximum int32
	BotID   int64
}

type DeliveryCandidatesRow struct {
	BotID        int64
	OwnerKind    string
	OwnerKey     string
	EffectKey    string
	Chat         string
	ThreadID     int64
	LaneSequence int64
	TrafficClass string
	State        string
	NotBefore    pgtype.Timestamptz
}

func (q *Queries) DeliveryCandidates(ctx context.Context, arg DeliveryCandidatesParams) ([]DeliveryCandidatesRow, error) {
	rows, err := q.db.Query(ctx, deliveryCandidates, arg.Maximum, arg.BotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeliveryCandidatesRow{}
	for rows.Next() {
		var i DeliveryCandidatesRow
		if err := rows.Scan(
			&i.BotID,
			&i.OwnerKind,
			&i.OwnerKey,
			&i.EffectKey,
			&i.Chat,
			&i.ThreadID,
			&i.LaneSequence,
			&i.TrafficClass,
			&i.State,
			&i.NotBefore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ensureDeliveryLane = `-- name: EnsureDeliveryLane :exec
INSERT INTO core.delivery_lanes(bot_id,chat) VALUES($1::bigint,$2::text)
ON CONFLICT DO NOTHING
`

type EnsureDeliveryLaneParams struct {
	BotID int64
	Chat  string
}

func (q *Queries) EnsureDeliveryLane(ctx context.Context, arg EnsureDeliveryLaneParams) error {
	_, err := q.db.Exec(ctx, ensureDeliveryLane, arg.BotID, arg.Chat)
	return err
}

const insertDeliveryEntry = `-- name: InsertDeliveryEntry :exec
INSERT INTO core.delivery_queue(bot_id,owner_kind,owner_key,effect_key,chat,thread_id,lane_sequence,traffic_class)
VALUES($1::bigint,$2::text,$3::text,$4::text,
 $5::text,$6::bigint,$7::bigint,$8::text)
ON CONFLICT(bot_id,owner_kind,owner_key,effect_key) DO NOTHING
`

type InsertDeliveryEntryParams struct {
	BotID        int64
	OwnerKind    string
	OwnerKey     string
	EffectKey    string
	Chat         string
	ThreadID     int64
	LaneSequence int64
	TrafficClass string
}

func (q *Queries) InsertDeliveryEntry(ctx context.Context, arg InsertDeliveryEntryParams) error {
	_, err := q.db.Exec(ctx, insertDeliveryEntry,
		arg.BotID,
		arg.OwnerKind,
		arg.OwnerKey,
		arg.EffectKey,
		arg.Chat,
		arg.ThreadID,
		arg.LaneSequence,
		arg.TrafficClass,
	)
	return err
}

const isDeliveryHead = `-- name: IsDeliveryHead :one
SELECT NOT EXISTS(SELECT 1 FROM core.delivery_queue
 WHERE bot_id=$1::bigint AND chat=$2::text AND lane_sequence<$3::bigint
 AND state IN ('pending','sending','unknown','parked','paused'))::boolean AS head
`

type IsDeliveryHeadParams struct {
	BotID        int64
	Chat         string
	LaneSequence int64
}

func (q *Queries) IsDeliveryHead(ctx context.Context, arg IsDeliveryHeadParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, isDeliveryHead, arg.BotID, arg.Chat, arg.LaneSequence)
	var head pgtype.Bool
	err := row.Scan(&head)
	return head, err
}

const lockDeliveryEntry = `-- name: LockDeliveryEntry :one
SELECT bot_id, owner_kind, owner_key, effect_key, chat, thread_id, lane_sequence, traffic_class, state, not_before FROM core.delivery_queue WHERE bot_id=$1::bigint
AND owner_kind=$2::text AND owner_key=$3::text AND effect_key=$4::text
FOR UPDATE
`

type LockDeliveryEntryParams struct {
	BotID     int64
	OwnerKind string
	OwnerKey  string
	EffectKey string
}

func (q *Queries) LockDeliveryEntry(ctx context.Context, arg LockDeliveryEntryParams) (CoreDeliveryQueue, error) {
	row := q.db.QueryRow(ctx, lockDeliveryEntry,
		arg.BotID,
		arg.OwnerKind,
		arg.OwnerKey,
		arg.EffectKey,
	)
	var i CoreDeliveryQueue
	err := row.Scan(
		&i.BotID,
		&i.OwnerKind,
		&i.OwnerKey,
		&i.EffectKey,
		&i.Chat,
		&i.ThreadID,
		&i.LaneSequence,
		&i.TrafficClass,
		&i.State,
		&i.NotBefore,
	)
	return i, err
}

const lockDeliveryLane = `-- name: LockDeliveryLane :one
SELECT next_sequence FROM core.delivery_lanes
WHERE bot_id=$1::bigint AND chat=$2::text FOR UPDATE
`

type LockDeliveryLaneParams struct {
	BotID int64
	Chat  string
}

func (q *Queries) LockDeliveryLane(ctx context.Context, arg LockDeliveryLaneParams) (int64, error) {
	row := q.db.QueryRow(ctx, lockDeliveryLane, arg.BotID, arg.Chat)
	var next_sequence int64
	err := row.Scan(&next_sequence)
	return next_sequence, err
}

const markDeliveryLaneServed = `-- name: MarkDeliveryLaneServed :exec
UPDATE core.delivery_lanes SET last_served=$1::bigint
WHERE bot_id=$2::bigint AND chat=$3::text
`

type MarkDeliveryLaneServedParams struct {
	Grants int64
	BotID  int64
	Chat   string
}

func (q *Queries) MarkDeliveryLaneServed(ctx context.Context, arg MarkDeliveryLaneServedParams) error {
	_, err := q.db.Exec(ctx, markDeliveryLaneServed, arg.Grants, arg.BotID, arg.Chat)
	return err
}

const projectDeliveryEntry = `-- name: ProjectDeliveryEntry :execrows
UPDATE core.delivery_queue SET state=$1::text,not_before=$2::timestamptz
WHERE bot_id=$3::bigint AND owner_kind=$4::text
AND owner_key=$5::text AND effect_key=$6::text
`

type ProjectDeliveryEntryParams struct {
	State     string
	NotBefore pgtype.Timestamptz
	BotID     int64
	OwnerKind string
	OwnerKey  string
	EffectKey string
}

func (q *Queries) ProjectDeliveryEntry(ctx context.Context, arg ProjectDeliveryEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, projectDeliveryEntry,
		arg.State,
		arg.NotBefore,
		arg.BotID,
		arg.OwnerKind,
		arg.OwnerKey,
		arg.EffectKey,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const readDeliveryEntry = `-- name: ReadDeliveryEntry :one
SELECT bot_id, owner_kind, owner_key, effect_key, chat, thread_id, lane_sequence, traffic_class, state, not_before FROM core.delivery_queue WHERE bot_id=$1::bigint
AND owner_kind=$2::text AND owner_key=$3::text AND effect_key=$4::text
`

type ReadDeliveryEntryParams struct {
	BotID     int64
	OwnerKind string
	OwnerKey  string
	EffectKey string
}

func (q *Queries) ReadDeliveryEntry(ctx context.Context, arg ReadDeliveryEntryParams) (CoreDeliveryQueue, error) {
	row := q.db.QueryRow(ctx, readDeliveryEntry,
		arg.BotID,
		arg.OwnerKind,
		arg.OwnerKey,
		arg.EffectKey,
	)
	var i CoreDeliveryQueue
	err := row.Scan(
		&i.BotID,
		&i.OwnerKind,
		&i.OwnerKey,
		&i.EffectKey,
		&i.Chat,
		&i.ThreadID,
		&i.LaneSequence,
		&i.TrafficClass,
		&i.State,
		&i.NotBefore,
	)
	return i, err
}
