// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_delivery.sql

package dbgen

import (
	"context"
)

const massageNotificationViewOpened = `-- name: MassageNotificationViewOpened :one
SELECT EXISTS(SELECT 1 FROM bot.massage_views WHERE owner=$1::text)::boolean
`

func (q *Queries) MassageNotificationViewOpened(ctx context.Context, owner string) (bool, error) {
	row := q.db.QueryRow(ctx, massageNotificationViewOpened, owner)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const storeFoodNotificationReceipt = `-- name: StoreFoodNotificationReceipt :exec
INSERT INTO bot.order_cards(owner,card_key,chat_id,message_id,view_hash)
VALUES($1::text,$2::text,$3::bigint,$4::bigint,'')
ON CONFLICT(owner,card_key) DO NOTHING
`

type StoreFoodNotificationReceiptParams struct {
	Owner     string
	Key       string
	Chat      int64
	MessageID int64
}

func (q *Queries) StoreFoodNotificationReceipt(ctx context.Context, arg StoreFoodNotificationReceiptParams) error {
	_, err := q.db.Exec(ctx, storeFoodNotificationReceipt,
		arg.Owner,
		arg.Key,
		arg.Chat,
		arg.MessageID,
	)
	return err
}

const storeMassageNotificationReceipt = `-- name: StoreMassageNotificationReceipt :exec
INSERT INTO bot.massage_deliveries(notice_id,message_id) VALUES($1::bigint,$2::bigint) ON CONFLICT DO NOTHING
`

type StoreMassageNotificationReceiptParams struct {
	ID        int64
	MessageID int64
}

func (q *Queries) StoreMassageNotificationReceipt(ctx context.Context, arg StoreMassageNotificationReceiptParams) error {
	_, err := q.db.Exec(ctx, storeMassageNotificationReceipt, arg.ID, arg.MessageID)
	return err
}

const storeOrderNotificationReceipt = `-- name: StoreOrderNotificationReceipt :exec
INSERT INTO bot.notification_deliveries(id,message_id) VALUES($1::bigint,$2::bigint) ON CONFLICT DO NOTHING
`

type StoreOrderNotificationReceiptParams struct {
	ID        int64
	MessageID int64
}

func (q *Queries) StoreOrderNotificationReceipt(ctx context.Context, arg StoreOrderNotificationReceiptParams) error {
	_, err := q.db.Exec(ctx, storeOrderNotificationReceipt, arg.ID, arg.MessageID)
	return err
}

const storePassNotificationReceipt = `-- name: StorePassNotificationReceipt :exec
INSERT INTO bot.pass_notification_deliveries(notice_id,message_id) VALUES($1::bigint,$2::bigint) ON CONFLICT DO NOTHING
`

type StorePassNotificationReceiptParams struct {
	ID        int64
	MessageID int64
}

func (q *Queries) StorePassNotificationReceipt(ctx context.Context, arg StorePassNotificationReceiptParams) error {
	_, err := q.db.Exec(ctx, storePassNotificationReceipt, arg.ID, arg.MessageID)
	return err
}
