// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CoreMassageNotice struct {
	ID                int64
	BookingID         string
	Owner             string
	Kind              string
	CreatedAt         pgtype.Timestamptz
	SentAt            pgtype.Timestamptz
	BotID             pgtype.Int8
	DeliveryState     string
	DeliveryChat      int64
	DeliveryAttempt   int64
	LeaseUntil        pgtype.Timestamptz
	TelegramMessageID int64
	DeliveryText      string
	FailureCount      int64
	FollowupPending   bool
	FollowupFailure   string
	FollowupAttempts  int64
	AvailableAt       pgtype.Timestamptz
	Failure           string
}
