// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_delivery.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const beginNotificationSend = `-- name: BeginNotificationSend :execrows
UPDATE core.massage_notices SET delivery_state='sending',lease_until=clock_timestamp()+interval '2 minutes'
WHERE id=$1::bigint AND bot_id=$2::bigint AND delivery_attempt=$3::bigint
AND delivery_state='pending' AND lease_until>clock_timestamp()
`

type BeginNotificationSendParams struct {
	ID      int64
	BotID   int64
	Attempt int64
}

func (q *Queries) BeginNotificationSend(ctx context.Context, arg BeginNotificationSendParams) (int64, error) {
	result, err := q.db.Exec(ctx, beginNotificationSend, arg.ID, arg.BotID, arg.Attempt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueNotification = `-- name: EnqueueNotification :one
INSERT INTO core.massage_notices(booking_id,owner,kind,bot_id,delivery_chat)
VALUES($1::text,$2::text,$3::text,
 CASE WHEN $4::bigint>0 THEN $4::bigint END,COALESCE((SELECT telegram_id FROM core.users WHERE id=$2::text),0)) ON CONFLICT DO NOTHING RETURNING id, booking_id, owner, kind, created_at, sent_at, bot_id, delivery_state, delivery_chat, delivery_attempt, lease_until, telegram_message_id, delivery_text, failure_count, followup_pending, followup_failure, followup_attempts, available_at, failure
`

type EnqueueNotificationParams struct {
	BookingID string
	Owner     string
	Kind      string
	BotID     int64
}

func (q *Queries) EnqueueNotification(ctx context.Context, arg EnqueueNotificationParams) (CoreMassageNotice, error) {
	row := q.db.QueryRow(ctx, enqueueNotification,
		arg.BookingID,
		arg.Owner,
		arg.Kind,
		arg.BotID,
	)
	var i CoreMassageNotice
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.Owner,
		&i.Kind,
		&i.CreatedAt,
		&i.SentAt,
		&i.BotID,
		&i.DeliveryState,
		&i.DeliveryChat,
		&i.DeliveryAttempt,
		&i.LeaseUntil,
		&i.TelegramMessageID,
		&i.DeliveryText,
		&i.FailureCount,
		&i.FollowupPending,
		&i.FollowupFailure,
		&i.FollowupAttempts,
		&i.AvailableAt,
		&i.Failure,
	)
	return i, err
}

const expiredNotification = `-- name: ExpiredNotification :one
SELECT id, booking_id, owner, kind, created_at, sent_at, bot_id, delivery_state, delivery_chat, delivery_attempt, lease_until, telegram_message_id, delivery_text, failure_count, followup_pending, followup_failure, followup_attempts, available_at, failure FROM core.massage_notices
WHERE bot_id=$1::bigint AND delivery_state='sending' AND lease_until<=clock_timestamp()
ORDER BY id LIMIT 1 FOR UPDATE SKIP LOCKED
`

func (q *Queries) ExpiredNotification(ctx context.Context, botID int64) (CoreMassageNotice, error) {
	row := q.db.QueryRow(ctx, expiredNotification, botID)
	var i CoreMassageNotice
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.Owner,
		&i.Kind,
		&i.CreatedAt,
		&i.SentAt,
		&i.BotID,
		&i.DeliveryState,
		&i.DeliveryChat,
		&i.DeliveryAttempt,
		&i.LeaseUntil,
		&i.TelegramMessageID,
		&i.DeliveryText,
		&i.FailureCount,
		&i.FollowupPending,
		&i.FollowupFailure,
		&i.FollowupAttempts,
		&i.AvailableAt,
		&i.Failure,
	)
	return i, err
}

const finishNotificationDelivery = `-- name: FinishNotificationDelivery :execrows
UPDATE core.massage_notices SET delivery_state=$1::text,
 telegram_message_id=$2::bigint,delivery_text=$3::text,failure=$4::text,
 available_at=$5::timestamptz,
 lease_until=CASE WHEN $1::text='sent' THEN clock_timestamp()+interval '2 minutes' END,
 followup_pending=($1::text='sent'),
 failure_count=failure_count+$6::bigint,
 sent_at=CASE WHEN $1::text IN ('failed','cancelled') THEN clock_timestamp() END
WHERE id=$7::bigint AND bot_id=$8::bigint AND delivery_attempt=$9::bigint
AND delivery_state IN ('pending','sending','unknown')
`

type FinishNotificationDeliveryParams struct {
	State            string
	MessageID        int64
	Text             string
	Failure          string
	AvailableAt      pgtype.Timestamptz
	FailureIncrement int64
	ID               int64
	BotID            int64
	Attempt          int64
}

func (q *Queries) FinishNotificationDelivery(ctx context.Context, arg FinishNotificationDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishNotificationDelivery,
		arg.State,
		arg.MessageID,
		arg.Text,
		arg.Failure,
		arg.AvailableAt,
		arg.FailureIncrement,
		arg.ID,
		arg.BotID,
		arg.Attempt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishNotificationFollowup = `-- name: FinishNotificationFollowup :execrows
UPDATE core.massage_notices SET followup_pending=NOT $1::boolean,
 followup_failure=$2::text,followup_attempts=followup_attempts+1,
 available_at=$3::timestamptz,lease_until=NULL,
 sent_at=CASE WHEN $1::boolean THEN clock_timestamp() END
WHERE id=$4::bigint AND bot_id=$5::bigint AND delivery_attempt=$6::bigint
AND delivery_state='sent' AND followup_pending
`

type FinishNotificationFollowupParams struct {
	Done        bool
	Failure     string
	AvailableAt pgtype.Timestamptz
	ID          int64
	BotID       int64
	Attempt     int64
}

func (q *Queries) FinishNotificationFollowup(ctx context.Context, arg FinishNotificationFollowupParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishNotificationFollowup,
		arg.Done,
		arg.Failure,
		arg.AvailableAt,
		arg.ID,
		arg.BotID,
		arg.Attempt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lockNotificationAttempt = `-- name: LockNotificationAttempt :one
SELECT id, booking_id, owner, kind, created_at, sent_at, bot_id, delivery_state, delivery_chat, delivery_attempt, lease_until, telegram_message_id, delivery_text, failure_count, followup_pending, followup_failure, followup_attempts, available_at, failure,COALESCE(lease_until>clock_timestamp(),false)::boolean AS lease_live FROM core.massage_notices
WHERE id=$1::bigint AND bot_id=$2::bigint AND delivery_attempt=$3::bigint FOR UPDATE
`

type LockNotificationAttemptParams struct {
	ID      int64
	BotID   int64
	Attempt int64
}

type LockNotificationAttemptRow struct {
	ID                int64
	BookingID         string
	Owner             string
	Kind              string
	CreatedAt         pgtype.Timestamptz
	SentAt            pgtype.Timestamptz
	BotID             pgtype.Int8
	DeliveryState     string
	DeliveryChat      int64
	DeliveryAttempt   int64
	LeaseUntil        pgtype.Timestamptz
	TelegramMessageID int64
	DeliveryText      string
	FailureCount      int64
	FollowupPending   bool
	FollowupFailure   string
	FollowupAttempts  int64
	AvailableAt       pgtype.Timestamptz
	Failure           string
	LeaseLive         bool
}

func (q *Queries) LockNotificationAttempt(ctx context.Context, arg LockNotificationAttemptParams) (LockNotificationAttemptRow, error) {
	row := q.db.QueryRow(ctx, lockNotificationAttempt, arg.ID, arg.BotID, arg.Attempt)
	var i LockNotificationAttemptRow
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.Owner,
		&i.Kind,
		&i.CreatedAt,
		&i.SentAt,
		&i.BotID,
		&i.DeliveryState,
		&i.DeliveryChat,
		&i.DeliveryAttempt,
		&i.LeaseUntil,
		&i.TelegramMessageID,
		&i.DeliveryText,
		&i.FailureCount,
		&i.FollowupPending,
		&i.FollowupFailure,
		&i.FollowupAttempts,
		&i.AvailableAt,
		&i.Failure,
		&i.LeaseLive,
	)
	return i, err
}

const lockNotificationBooking = `-- name: LockNotificationBooking :one
SELECT b.id FROM core.massage_bookings b JOIN core.massage_specialists sp ON sp.event_id=b.event_id AND sp.owner=b.specialist
WHERE b.id=$1::text FOR SHARE OF b,sp
`

func (q *Queries) LockNotificationBooking(ctx context.Context, booking string) (string, error) {
	row := q.db.QueryRow(ctx, lockNotificationBooking, booking)
	var id string
	err := row.Scan(&id)
	return id, err
}

const lockNotificationRecipient = `-- name: LockNotificationRecipient :one
SELECT telegram_id,can_book FROM core.users WHERE id=$1::text FOR SHARE
`

type LockNotificationRecipientRow struct {
	TelegramID int64
	CanBook    bool
}

func (q *Queries) LockNotificationRecipient(ctx context.Context, owner string) (LockNotificationRecipientRow, error) {
	row := q.db.QueryRow(ctx, lockNotificationRecipient, owner)
	var i LockNotificationRecipientRow
	err := row.Scan(&i.TelegramID, &i.CanBook)
	return i, err
}

const missingNotificationIndex = `-- name: MissingNotificationIndex :one
SELECT EXISTS(SELECT 1 FROM core.massage_notices n
WHERE n.bot_id=$1::bigint AND n.delivery_chat<>0
AND (n.delivery_state IN ('pending','sending','unknown','parked','paused') OR n.followup_pending)
AND NOT EXISTS(SELECT 1 FROM core.delivery_queue q WHERE q.bot_id=n.bot_id
 AND q.owner_kind='massage' AND q.owner_key=n.id::text AND q.effect_key='send'))::boolean
`

func (q *Queries) MissingNotificationIndex(ctx context.Context, botID int64) (bool, error) {
	row := q.db.QueryRow(ctx, missingNotificationIndex, botID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const notificationBookingProjection = `-- name: NotificationBookingProjection :one
SELECT b.id,b.starts_at,b.ends_at,b.length,b.price,b.cancelled_at,u.name AS client,sp.name AS specialist
FROM core.massage_bookings b JOIN core.users u ON u.id=b.owner
JOIN core.massage_specialists sp ON sp.event_id=b.event_id AND sp.owner=b.specialist
WHERE b.id=$1::text
`

type NotificationBookingProjectionRow struct {
	ID          string
	StartsAt    pgtype.Timestamptz
	EndsAt      pgtype.Timestamptz
	Length      int32
	Price       int32
	CancelledAt pgtype.Timestamptz
	Client      string
	Specialist  string
}

func (q *Queries) NotificationBookingProjection(ctx context.Context, booking string) (NotificationBookingProjectionRow, error) {
	row := q.db.QueryRow(ctx, notificationBookingProjection, booking)
	var i NotificationBookingProjectionRow
	err := row.Scan(
		&i.ID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Length,
		&i.Price,
		&i.CancelledAt,
		&i.Client,
		&i.Specialist,
	)
	return i, err
}

const notificationCurrent = `-- name: NotificationCurrent :one
SELECT (u.can_book AND (b.cancelled_at IS NULL OR n.kind='cancelled')
 AND (n.kind NOT IN ('booked','cancelled') OR sp.notify_bookings)
 AND (n.kind<>'next' OR sp.notify_next)
 AND (n.kind<>'additional' OR b.starts_at>=$1::timestamptz))::boolean AS current
FROM core.massage_notices n JOIN core.massage_bookings b ON b.id=n.booking_id
JOIN core.massage_specialists sp ON sp.event_id=b.event_id AND sp.owner=b.specialist
JOIN core.users u ON u.id=n.owner WHERE n.id=$2::bigint AND n.bot_id=$3::bigint
`

type NotificationCurrentParams struct {
	Now   pgtype.Timestamptz
	ID    int64
	BotID int64
}

func (q *Queries) NotificationCurrent(ctx context.Context, arg NotificationCurrentParams) (bool, error) {
	row := q.db.QueryRow(ctx, notificationCurrent, arg.Now, arg.ID, arg.BotID)
	var current bool
	err := row.Scan(&current)
	return current, err
}

const notificationRecipients = `-- name: NotificationRecipients :many
SELECT n.owner,u.telegram_id FROM core.massage_notices n
JOIN core.users u ON u.id=n.owner
LEFT JOIN core.massage_notification_attempts a ON a.owner=n.owner
WHERE n.bot_id=$1::bigint
AND (n.delivery_state='pending' OR (n.delivery_state='sent' AND n.followup_pending))
AND n.available_at<=clock_timestamp() AND (n.lease_until IS NULL OR n.lease_until<=clock_timestamp())
GROUP BY n.owner,u.telegram_id,a.attempted_at
ORDER BY a.attempted_at NULLS FIRST,n.owner LIMIT 100
`

type NotificationRecipientsRow struct {
	Owner      string
	TelegramID int64
}

func (q *Queries) NotificationRecipients(ctx context.Context, botID int64) ([]NotificationRecipientsRow, error) {
	rows, err := q.db.Query(ctx, notificationRecipients, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationRecipientsRow{}
	for rows.Next() {
		var i NotificationRecipientsRow
		if err := rows.Scan(&i.Owner, &i.TelegramID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notificationReminderEvents = `-- name: NotificationReminderEvents :many
SELECT DISTINCT event_id FROM core.massage_parties
WHERE starts_at-interval '2 hours'<$1::timestamptz AND ends_at+interval '2 hours'>$1::timestamptz
`

func (q *Queries) NotificationReminderEvents(ctx context.Context, now pgtype.Timestamptz) ([]string, error) {
	rows, err := q.db.Query(ctx, notificationReminderEvents, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var event_id string
		if err := rows.Scan(&event_id); err != nil {
			return nil, err
		}
		items = append(items, event_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pauseUnroutableNotification = `-- name: PauseUnroutableNotification :exec
UPDATE core.massage_notices SET delivery_state='paused',failure='notification_identity_unavailable'
WHERE id=$1::bigint AND delivery_state='pending' AND (bot_id IS NULL OR delivery_chat=0)
`

func (q *Queries) PauseUnroutableNotification(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, pauseUnroutableNotification, id)
	return err
}

const prepareNotification = `-- name: PrepareNotification :one
WITH head AS (
 SELECT n.id,COALESCE(u.telegram_id,0)::bigint AS chat FROM core.massage_notices n JOIN core.users u ON u.id=n.owner
 WHERE n.bot_id=$1::bigint
 AND ($2::bigint=0 OR n.id=$2::bigint)
 AND (NOT $3::boolean OR (n.delivery_state='sent' AND n.followup_pending))
 AND ($4::text='' OR n.owner=$4::text)
 AND (n.delivery_state='pending' OR (n.delivery_state='sent' AND n.followup_pending))
 AND n.available_at<=clock_timestamp() AND (n.lease_until IS NULL OR n.lease_until<=clock_timestamp())
 AND NOT EXISTS(SELECT 1 FROM core.massage_notices older
  JOIN core.delivery_queue oq ON oq.bot_id=older.bot_id AND oq.owner_kind='massage'
   AND oq.owner_key=older.id::text AND oq.effect_key='send'
  JOIN core.delivery_queue nq ON nq.bot_id=n.bot_id AND nq.owner_kind='massage'
   AND nq.owner_key=n.id::text AND nq.effect_key='send'
  WHERE older.bot_id=n.bot_id AND older.delivery_chat=n.delivery_chat
   AND older.followup_pending AND oq.lane_sequence<nq.lane_sequence)
 AND (n.delivery_state='sent' OR EXISTS(SELECT 1 FROM core.delivery_queue q
  WHERE q.bot_id=n.bot_id AND q.owner_kind='massage' AND q.owner_key=n.id::text AND q.effect_key='send'
  AND NOT EXISTS(SELECT 1 FROM core.delivery_queue previous WHERE previous.bot_id=q.bot_id
   AND previous.chat=q.chat AND previous.lane_sequence<q.lane_sequence
   AND previous.state IN ('pending','sending','unknown','parked','paused'))))
 ORDER BY n.available_at,n.id LIMIT 1 FOR UPDATE OF n SKIP LOCKED
)
UPDATE core.massage_notices n SET delivery_attempt=delivery_attempt+1,lease_until=clock_timestamp()+interval '2 minutes'
FROM head WHERE n.id=head.id RETURNING n.id, n.booking_id, n.owner, n.kind, n.created_at, n.sent_at, n.bot_id, n.delivery_state, n.delivery_chat, n.delivery_attempt, n.lease_until, n.telegram_message_id, n.delivery_text, n.failure_count, n.followup_pending, n.followup_failure, n.followup_attempts, n.available_at, n.failure
`

type PrepareNotificationParams struct {
	BotID        int64
	ID           int64
	FollowupOnly bool
	Owner        string
}

func (q *Queries) PrepareNotification(ctx context.Context, arg PrepareNotificationParams) (CoreMassageNotice, error) {
	row := q.db.QueryRow(ctx, prepareNotification,
		arg.BotID,
		arg.ID,
		arg.FollowupOnly,
		arg.Owner,
	)
	var i CoreMassageNotice
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.Owner,
		&i.Kind,
		&i.CreatedAt,
		&i.SentAt,
		&i.BotID,
		&i.DeliveryState,
		&i.DeliveryChat,
		&i.DeliveryAttempt,
		&i.LeaseUntil,
		&i.TelegramMessageID,
		&i.DeliveryText,
		&i.FailureCount,
		&i.FollowupPending,
		&i.FollowupFailure,
		&i.FollowupAttempts,
		&i.AvailableAt,
		&i.Failure,
	)
	return i, err
}

const queueNotificationReminders = `-- name: QueueNotificationReminders :many
INSERT INTO core.massage_notices(booking_id,owner,kind,bot_id,delivery_chat)
	SELECT b.id,n.owner,n.kind,CASE WHEN $1::bigint>0 THEN $1::bigint END,COALESCE((SELECT telegram_id FROM core.users WHERE id=n.owner),0) FROM core.massage_bookings b
	JOIN core.massage_events e ON e.id=b.event_id
	JOIN core.massage_specialists sp ON sp.event_id=b.event_id AND sp.owner=b.specialist
	CROSS JOIN LATERAL (VALUES
	 (b.owner,'prior_long',e.prior_long,true),
	 (b.owner,'prior_short',e.prior_short,true),
	 (b.specialist,'next',interval '5 minutes',sp.notify_next)) n(owner,kind,prior,enabled)
	WHERE b.event_id=$2::text AND b.cancelled_at IS NULL AND n.enabled
	AND b.starts_at >= (SELECT min(p.starts_at)-interval '2 hours' FROM core.massage_parties p WHERE p.event_id=b.event_id)
	AND b.starts_at<$3::timestamptz+n.prior
	ON CONFLICT DO NOTHING RETURNING id, booking_id, owner, kind, created_at, sent_at, bot_id, delivery_state, delivery_chat, delivery_attempt, lease_until, telegram_message_id, delivery_text, failure_count, followup_pending, followup_failure, followup_attempts, available_at, failure
`

type QueueNotificationRemindersParams struct {
	BotID int64
	Event string
	Now   pgtype.Timestamptz
}

func (q *Queries) QueueNotificationReminders(ctx context.Context, arg QueueNotificationRemindersParams) ([]CoreMassageNotice, error) {
	rows, err := q.db.Query(ctx, queueNotificationReminders, arg.BotID, arg.Event, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreMassageNotice{}
	for rows.Next() {
		var i CoreMassageNotice
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.Owner,
			&i.Kind,
			&i.CreatedAt,
			&i.SentAt,
			&i.BotID,
			&i.DeliveryState,
			&i.DeliveryChat,
			&i.DeliveryAttempt,
			&i.LeaseUntil,
			&i.TelegramMessageID,
			&i.DeliveryText,
			&i.FailureCount,
			&i.FollowupPending,
			&i.FollowupFailure,
			&i.FollowupAttempts,
			&i.AvailableAt,
			&i.Failure,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readNotification = `-- name: ReadNotification :one
SELECT id, booking_id, owner, kind, created_at, sent_at, bot_id, delivery_state, delivery_chat, delivery_attempt, lease_until, telegram_message_id, delivery_text, failure_count, followup_pending, followup_failure, followup_attempts, available_at, failure FROM core.massage_notices WHERE id=$1::bigint AND bot_id=$2::bigint
`

type ReadNotificationParams struct {
	ID    int64
	BotID int64
}

func (q *Queries) ReadNotification(ctx context.Context, arg ReadNotificationParams) (CoreMassageNotice, error) {
	row := q.db.QueryRow(ctx, readNotification, arg.ID, arg.BotID)
	var i CoreMassageNotice
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.Owner,
		&i.Kind,
		&i.CreatedAt,
		&i.SentAt,
		&i.BotID,
		&i.DeliveryState,
		&i.DeliveryChat,
		&i.DeliveryAttempt,
		&i.LeaseUntil,
		&i.TelegramMessageID,
		&i.DeliveryText,
		&i.FailureCount,
		&i.FollowupPending,
		&i.FollowupFailure,
		&i.FollowupAttempts,
		&i.AvailableAt,
		&i.Failure,
	)
	return i, err
}

const recordNotificationRotation = `-- name: RecordNotificationRotation :exec
INSERT INTO core.massage_notification_attempts(owner,attempted_at)
SELECT id,clock_timestamp() FROM core.users WHERE id=$1::text
ON CONFLICT(owner) DO UPDATE SET attempted_at=EXCLUDED.attempted_at
`

func (q *Queries) RecordNotificationRotation(ctx context.Context, owner string) error {
	_, err := q.db.Exec(ctx, recordNotificationRotation, owner)
	return err
}
