// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delivery.sql

package dbgen

import (
	"context"
	"time"
)

const completeBotDeliveryReceipt = `-- name: CompleteBotDeliveryReceipt :exec
UPDATE bot.delivery_intents SET continuation_done=true
WHERE bot_id=$1 AND operation_key=$2 AND effect_key=$3 AND state='sent' AND message_id=$4
`

type CompleteBotDeliveryReceiptParams struct {
	BotID        int64
	OperationKey string
	EffectKey    string
	MessageID    int64
}

func (q *Queries) CompleteBotDeliveryReceipt(ctx context.Context, arg CompleteBotDeliveryReceiptParams) error {
	_, err := q.db.Exec(ctx, completeBotDeliveryReceipt,
		arg.BotID,
		arg.OperationKey,
		arg.EffectKey,
		arg.MessageID,
	)
	return err
}

const getBotDeliveryIntent = `-- name: GetBotDeliveryIntent :one
SELECT bot_id,operation_key,effect_key,owner,chat_id,reference,state,phase,
 target_message_id,attempt,not_before,message_id,continuation_done,receipt
FROM bot.delivery_intents WHERE bot_id=$1 AND operation_key=$2 AND effect_key=$3
`

type GetBotDeliveryIntentParams struct {
	BotID        int64
	OperationKey string
	EffectKey    string
}

type GetBotDeliveryIntentRow struct {
	BotID            int64
	OperationKey     string
	EffectKey        string
	Owner            string
	ChatID           int64
	Reference        []byte
	State            string
	Phase            string
	TargetMessageID  int64
	Attempt          int64
	NotBefore        time.Time
	MessageID        int64
	ContinuationDone bool
	Receipt          []byte
}

func (q *Queries) GetBotDeliveryIntent(ctx context.Context, arg GetBotDeliveryIntentParams) (GetBotDeliveryIntentRow, error) {
	row := q.db.QueryRow(ctx, getBotDeliveryIntent, arg.BotID, arg.OperationKey, arg.EffectKey)
	var i GetBotDeliveryIntentRow
	err := row.Scan(
		&i.BotID,
		&i.OperationKey,
		&i.EffectKey,
		&i.Owner,
		&i.ChatID,
		&i.Reference,
		&i.State,
		&i.Phase,
		&i.TargetMessageID,
		&i.Attempt,
		&i.NotBefore,
		&i.MessageID,
		&i.ContinuationDone,
		&i.Receipt,
	)
	return i, err
}

const lockBotDeliveryIntent = `-- name: LockBotDeliveryIntent :one
SELECT bot_id,operation_key,effect_key,owner,chat_id,reference,state,phase,
 target_message_id,attempt,not_before,message_id,continuation_done,receipt
FROM bot.delivery_intents WHERE bot_id=$1 AND operation_key=$2 AND effect_key=$3 FOR UPDATE
`

type LockBotDeliveryIntentParams struct {
	BotID        int64
	OperationKey string
	EffectKey    string
}

type LockBotDeliveryIntentRow struct {
	BotID            int64
	OperationKey     string
	EffectKey        string
	Owner            string
	ChatID           int64
	Reference        []byte
	State            string
	Phase            string
	TargetMessageID  int64
	Attempt          int64
	NotBefore        time.Time
	MessageID        int64
	ContinuationDone bool
	Receipt          []byte
}

func (q *Queries) LockBotDeliveryIntent(ctx context.Context, arg LockBotDeliveryIntentParams) (LockBotDeliveryIntentRow, error) {
	row := q.db.QueryRow(ctx, lockBotDeliveryIntent, arg.BotID, arg.OperationKey, arg.EffectKey)
	var i LockBotDeliveryIntentRow
	err := row.Scan(
		&i.BotID,
		&i.OperationKey,
		&i.EffectKey,
		&i.Owner,
		&i.ChatID,
		&i.Reference,
		&i.State,
		&i.Phase,
		&i.TargetMessageID,
		&i.Attempt,
		&i.NotBefore,
		&i.MessageID,
		&i.ContinuationDone,
		&i.Receipt,
	)
	return i, err
}
