// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resolution.sql

package dbgen

import (
	"context"
)

const getBotDeliveryAttempt = `-- name: GetBotDeliveryAttempt :one
SELECT method,payload_sha256,continuation FROM bot.delivery_attempts
WHERE bot_id=$1 AND operation_key=$2 AND effect_key=$3 AND attempt=$4
`

type GetBotDeliveryAttemptParams struct {
	BotID        int64
	OperationKey string
	EffectKey    string
	Attempt      int64
}

type GetBotDeliveryAttemptRow struct {
	Method        string
	PayloadSha256 string
	Continuation  []byte
}

func (q *Queries) GetBotDeliveryAttempt(ctx context.Context, arg GetBotDeliveryAttemptParams) (GetBotDeliveryAttemptRow, error) {
	row := q.db.QueryRow(ctx, getBotDeliveryAttempt,
		arg.BotID,
		arg.OperationKey,
		arg.EffectKey,
		arg.Attempt,
	)
	var i GetBotDeliveryAttemptRow
	err := row.Scan(&i.Method, &i.PayloadSha256, &i.Continuation)
	return i, err
}

const getBotDeliveryResolution = `-- name: GetBotDeliveryResolution :one
SELECT request,result FROM bot.delivery_resolutions WHERE actor=$1 AND operation_key=$2
`

type GetBotDeliveryResolutionParams struct {
	Actor        string
	OperationKey string
}

type GetBotDeliveryResolutionRow struct {
	Request []byte
	Result  []byte
}

func (q *Queries) GetBotDeliveryResolution(ctx context.Context, arg GetBotDeliveryResolutionParams) (GetBotDeliveryResolutionRow, error) {
	row := q.db.QueryRow(ctx, getBotDeliveryResolution, arg.Actor, arg.OperationKey)
	var i GetBotDeliveryResolutionRow
	err := row.Scan(&i.Request, &i.Result)
	return i, err
}

const insertBotDeliveryAttempt = `-- name: InsertBotDeliveryAttempt :exec
INSERT INTO bot.delivery_attempts(bot_id,operation_key,effect_key,attempt,method,payload_sha256,continuation)
VALUES($1,$2,$3,$4,$5,$6,$7)
`

type InsertBotDeliveryAttemptParams struct {
	BotID         int64
	OperationKey  string
	EffectKey     string
	Attempt       int64
	Method        string
	PayloadSha256 string
	Continuation  []byte
}

func (q *Queries) InsertBotDeliveryAttempt(ctx context.Context, arg InsertBotDeliveryAttemptParams) error {
	_, err := q.db.Exec(ctx, insertBotDeliveryAttempt,
		arg.BotID,
		arg.OperationKey,
		arg.EffectKey,
		arg.Attempt,
		arg.Method,
		arg.PayloadSha256,
		arg.Continuation,
	)
	return err
}

const insertBotDeliveryResolution = `-- name: InsertBotDeliveryResolution :exec
INSERT INTO bot.delivery_resolutions(actor,operation_key,request,result) VALUES($1,$2,$3,$4)
`

type InsertBotDeliveryResolutionParams struct {
	Actor        string
	OperationKey string
	Request      []byte
	Result       []byte
}

func (q *Queries) InsertBotDeliveryResolution(ctx context.Context, arg InsertBotDeliveryResolutionParams) error {
	_, err := q.db.Exec(ctx, insertBotDeliveryResolution,
		arg.Actor,
		arg.OperationKey,
		arg.Request,
		arg.Result,
	)
	return err
}
