// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: native.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeNativeCandidate = `-- name: CompleteNativeCandidate :exec
UPDATE core.registration_ingress SET native_outcome=$1::text,
 native_intent_id=$2::bigint
WHERE id=$3::bigint AND native_outcome='' AND native_payload=$4::jsonb
`

type CompleteNativeCandidateParams struct {
	Outcome  string
	IntentID pgtype.Int8
	ID       int64
	Payload  []byte
}

func (q *Queries) CompleteNativeCandidate(ctx context.Context, arg CompleteNativeCandidateParams) error {
	_, err := q.db.Exec(ctx, completeNativeCandidate,
		arg.Outcome,
		arg.IntentID,
		arg.ID,
		arg.Payload,
	)
	return err
}

const lockNativeBinding = `-- name: LockNativeBinding :one
SELECT b.action,v.state,v.revision,v.owner
FROM bot.pass_views v JOIN bot.pass_buttons b ON b.owner=v.owner AND b.revision=v.revision
WHERE v.owner=$1::text AND v.chat_id=$2::bigint AND b.token=$3::text
 AND NOT COALESCE((v.state->>'redacted')::boolean,false)
FOR SHARE OF v,b
`

type LockNativeBindingParams struct {
	Owner  string
	ChatID int64
	Token  string
}

type LockNativeBindingRow struct {
	Action   []byte
	State    []byte
	Revision int64
	Owner    string
}

func (q *Queries) LockNativeBinding(ctx context.Context, arg LockNativeBindingParams) (LockNativeBindingRow, error) {
	row := q.db.QueryRow(ctx, lockNativeBinding, arg.Owner, arg.ChatID, arg.Token)
	var i LockNativeBindingRow
	err := row.Scan(
		&i.Action,
		&i.State,
		&i.Revision,
		&i.Owner,
	)
	return i, err
}

const nativeBindings = `-- name: NativeBindings :many
SELECT b.action,v.state,v.revision,v.owner
FROM bot.pass_views v JOIN bot.pass_buttons b ON b.owner=v.owner AND b.revision=v.revision
WHERE v.chat_id=$1::bigint AND b.token=$2::text
 AND NOT COALESCE((v.state->>'redacted')::boolean,false)
`

type NativeBindingsParams struct {
	ChatID int64
	Token  string
}

type NativeBindingsRow struct {
	Action   []byte
	State    []byte
	Revision int64
	Owner    string
}

func (q *Queries) NativeBindings(ctx context.Context, arg NativeBindingsParams) ([]NativeBindingsRow, error) {
	rows, err := q.db.Query(ctx, nativeBindings, arg.ChatID, arg.Token)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NativeBindingsRow{}
	for rows.Next() {
		var i NativeBindingsRow
		if err := rows.Scan(
			&i.Action,
			&i.State,
			&i.Revision,
			&i.Owner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nativePendingEvents = `-- name: NativePendingEvents :many
SELECT DISTINCT native_event::text AS event FROM core.registration_ingress
WHERE native_payload IS NOT NULL AND native_outcome='' ORDER BY native_event
`

func (q *Queries) NativePendingEvents(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, nativePendingEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var event string
		if err := rows.Scan(&event); err != nil {
			return nil, err
		}
		items = append(items, event)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingNativeCandidates = `-- name: PendingNativeCandidates :many
SELECT id,bot_id,request_key,telegram_id,received_at,native_payload
FROM core.registration_ingress WHERE native_event=$1::text
 AND native_payload IS NOT NULL AND native_outcome=''
ORDER BY id
`

type PendingNativeCandidatesRow struct {
	ID            int64
	BotID         int64
	RequestKey    string
	TelegramID    int64
	ReceivedAt    pgtype.Timestamptz
	NativePayload []byte
}

func (q *Queries) PendingNativeCandidates(ctx context.Context, event string) ([]PendingNativeCandidatesRow, error) {
	rows, err := q.db.Query(ctx, pendingNativeCandidates, event)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingNativeCandidatesRow{}
	for rows.Next() {
		var i PendingNativeCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.RequestKey,
			&i.TelegramID,
			&i.ReceivedAt,
			&i.NativePayload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
