telegram:
  token: "YOUR_TOKEN" # or ommit to use TELEGRAM_TOKEN from env

food:
  admins:
    - -1
  proover: 1
  storage_path: "menu"

server:
  base: "https://example.com/bot" # used for appending to local urls
  port: 8080 # server port

logging:
  level: "INFO" # or ommit to use LOGGING_LEVEL from env

photo:
  cpu_threads: 8
  storage_path: "photos"

