telegram:
  token: "YOUR_TOKEN" # or ommit to use TELEGRAM_TOKEN from env

logging:
  level: "INFO" # or ommit to use LOGGING_LEVEL from env

localization:
  path: "i18n/{locale}"
  fallbacks: ["en-US", "en"]
  file: bot.ftl

mongo_db:
  address: mongodb://admin:test@mongo:27017/bots_db
  collection: bots_users
