// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: announcements.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const announcementAttemptSource = `-- name: AnnouncementAttemptSource :one
SELECT event_id,owner FROM core.pass_registration_announcements
WHERE id=$1::bigint AND bot_id=$2::bigint AND attempts=$3::bigint
`

type AnnouncementAttemptSourceParams struct {
	ID      int64
	BotID   int64
	Attempt int64
}

type AnnouncementAttemptSourceRow struct {
	EventID string
	Owner   string
}

func (q *Queries) AnnouncementAttemptSource(ctx context.Context, arg AnnouncementAttemptSourceParams) (AnnouncementAttemptSourceRow, error) {
	row := q.db.QueryRow(ctx, announcementAttemptSource, arg.ID, arg.BotID, arg.Attempt)
	var i AnnouncementAttemptSourceRow
	err := row.Scan(&i.EventID, &i.Owner)
	return i, err
}

const beginAnnouncementSend = `-- name: BeginAnnouncementSend :execrows
UPDATE core.pass_registration_announcements SET state='sending',lease_until=clock_timestamp()+interval '2 minutes',
 uncertain_resends=uncertain_resends+CASE WHEN last_uncertain_attempt IS NOT NULL THEN 1 ELSE 0 END
WHERE id=$1::bigint AND bot_id=$2::bigint AND attempts=$3::bigint
 AND state='pending' AND lease_until>clock_timestamp()
 AND (last_uncertain_attempt IS NULL OR uncertain_resends<3)
`

type BeginAnnouncementSendParams struct {
	ID      int64
	BotID   int64
	Attempt int64
}

func (q *Queries) BeginAnnouncementSend(ctx context.Context, arg BeginAnnouncementSendParams) (int64, error) {
	result, err := q.db.Exec(ctx, beginAnnouncementSend, arg.ID, arg.BotID, arg.Attempt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueRegistrationAnnouncements = `-- name: EnqueueRegistrationAnnouncements :exec
INSERT INTO core.pass_registration_announcements(event_id,owner,created_at,channel,thread_id,locale,name,role,state,bot_id)
SELECT b.event_id,b.owner,b.created_at,e.thread_channel,e.thread_id,e.thread_locale,u.name,b.role,
 CASE WHEN e.thread_channel='' THEN 'suppressed' ELSE 'pending' END,CASE WHEN $1::bigint>0 THEN $1::bigint END
FROM core.pass_bookings b JOIN core.pass_events e ON e.id=b.event_id JOIN core.users u ON u.id=b.owner
WHERE b.event_id=$2::text AND (e.open_ended OR e.finishes_at>COALESCE($3::timestamptz,clock_timestamp()))
ON CONFLICT(event_id,owner,created_at) DO NOTHING
`

type EnqueueRegistrationAnnouncementsParams struct {
	BotID      int64
	EventID    string
	DomainTime pgtype.Timestamptz
}

func (q *Queries) EnqueueRegistrationAnnouncements(ctx context.Context, arg EnqueueRegistrationAnnouncementsParams) error {
	_, err := q.db.Exec(ctx, enqueueRegistrationAnnouncements, arg.BotID, arg.EventID, arg.DomainTime)
	return err
}

const expireAnnouncementSends = `-- name: ExpireAnnouncementSends :exec
UPDATE core.pass_registration_announcements SET state='unknown',failure='telegram_outcome_unknown'
WHERE bot_id=$1::bigint AND state='sending' AND lease_until<=clock_timestamp()
`

func (q *Queries) ExpireAnnouncementSends(ctx context.Context, botID int64) error {
	_, err := q.db.Exec(ctx, expireAnnouncementSends, botID)
	return err
}

const finishAnnouncement = `-- name: FinishAnnouncement :execrows
UPDATE core.pass_registration_announcements SET state=$1::text,
 message_id=$2::bigint,failure=$3::text,
 available_at=$4::timestamptz,lease_until=NULL,
 failure_count=failure_count+$5::bigint
WHERE id=$6::bigint AND bot_id=$7::bigint AND attempts=$8::bigint
 AND state IN ('pending','sending','unknown')
`

type FinishAnnouncementParams struct {
	State            string
	MessageID        int64
	Failure          string
	AvailableAt      pgtype.Timestamptz
	FailureIncrement int64
	ID               int64
	BotID            int64
	Attempt          int64
}

func (q *Queries) FinishAnnouncement(ctx context.Context, arg FinishAnnouncementParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishAnnouncement,
		arg.State,
		arg.MessageID,
		arg.Failure,
		arg.AvailableAt,
		arg.FailureIncrement,
		arg.ID,
		arg.BotID,
		arg.Attempt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lockAnnouncementAttempt = `-- name: LockAnnouncementAttempt :one
SELECT a.channel,a.thread_id,a.state,a.message_id,a.available_at,a.failure,
 a.last_uncertain_attempt,a.uncertain_resends,a.lease_until,
 COALESCE(a.lease_until>clock_timestamp(),false)::boolean AS lease_live,
 EXISTS(SELECT 1 FROM core.pass_events e JOIN core.pass_bookings b ON b.event_id=e.id
  WHERE e.id=a.event_id AND b.owner=a.owner AND b.created_at=a.created_at AND b.state<>'cancelled'
   AND (e.open_ended OR e.finishes_at>COALESCE($1::timestamptz,clock_timestamp()))
   AND e.thread_channel=a.channel AND COALESCE(e.thread_id,0)=COALESCE(a.thread_id,0))::boolean AS current
FROM core.pass_registration_announcements a WHERE a.id=$2::bigint
 AND a.bot_id=$3::bigint AND a.attempts=$4::bigint FOR UPDATE
`

type LockAnnouncementAttemptParams struct {
	DomainTime pgtype.Timestamptz
	ID         int64
	BotID      int64
	Attempt    int64
}

type LockAnnouncementAttemptRow struct {
	Channel              string
	ThreadID             pgtype.Int8
	State                string
	MessageID            int64
	AvailableAt          pgtype.Timestamptz
	Failure              string
	LastUncertainAttempt pgtype.Int8
	UncertainResends     int64
	LeaseUntil           pgtype.Timestamptz
	LeaseLive            bool
	Current              bool
}

func (q *Queries) LockAnnouncementAttempt(ctx context.Context, arg LockAnnouncementAttemptParams) (LockAnnouncementAttemptRow, error) {
	row := q.db.QueryRow(ctx, lockAnnouncementAttempt,
		arg.DomainTime,
		arg.ID,
		arg.BotID,
		arg.Attempt,
	)
	var i LockAnnouncementAttemptRow
	err := row.Scan(
		&i.Channel,
		&i.ThreadID,
		&i.State,
		&i.MessageID,
		&i.AvailableAt,
		&i.Failure,
		&i.LastUncertainAttempt,
		&i.UncertainResends,
		&i.LeaseUntil,
		&i.LeaseLive,
		&i.Current,
	)
	return i, err
}

const lockAnnouncementBooking = `-- name: LockAnnouncementBooking :one
SELECT owner FROM core.pass_bookings
WHERE event_id=$1::text AND owner=$2::text FOR SHARE
`

type LockAnnouncementBookingParams struct {
	EventID string
	Owner   string
}

func (q *Queries) LockAnnouncementBooking(ctx context.Context, arg LockAnnouncementBookingParams) (string, error) {
	row := q.db.QueryRow(ctx, lockAnnouncementBooking, arg.EventID, arg.Owner)
	var owner string
	err := row.Scan(&owner)
	return owner, err
}

const lockAnnouncementEvent = `-- name: LockAnnouncementEvent :one
SELECT id FROM core.pass_events WHERE id=$1::text FOR SHARE
`

func (q *Queries) LockAnnouncementEvent(ctx context.Context, eventID string) (string, error) {
	row := q.db.QueryRow(ctx, lockAnnouncementEvent, eventID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const prepareAnnouncement = `-- name: PrepareAnnouncement :one
WITH next AS (
 SELECT a.id FROM core.pass_registration_announcements a
 WHERE a.bot_id=$1::bigint AND a.state='pending' AND a.available_at<=clock_timestamp()
 AND (a.lease_until IS NULL OR a.lease_until<=clock_timestamp())
 AND NOT EXISTS(SELECT 1 FROM core.pass_registration_announcements earlier
  WHERE (earlier.bot_id=a.bot_id OR earlier.bot_id IS NULL) AND earlier.channel=a.channel
   AND COALESCE(earlier.thread_id,0)=COALESCE(a.thread_id,0) AND earlier.id<a.id
   AND earlier.state IN ('pending','sending','unknown','parked','paused'))
 ORDER BY a.id FOR UPDATE SKIP LOCKED LIMIT 1
)
UPDATE core.pass_registration_announcements a
SET attempts=attempts+1,lease_until=clock_timestamp()+interval '2 minutes'
FROM next WHERE a.id=next.id RETURNING a.id,a.channel,a.thread_id,a.locale,a.name,a.role,a.attempts
`

type PrepareAnnouncementRow struct {
	ID       int64
	Channel  string
	ThreadID pgtype.Int8
	Locale   string
	Name     string
	Role     string
	Attempts int64
}

func (q *Queries) PrepareAnnouncement(ctx context.Context, botID int64) (PrepareAnnouncementRow, error) {
	row := q.db.QueryRow(ctx, prepareAnnouncement, botID)
	var i PrepareAnnouncementRow
	err := row.Scan(
		&i.ID,
		&i.Channel,
		&i.ThreadID,
		&i.Locale,
		&i.Name,
		&i.Role,
		&i.Attempts,
	)
	return i, err
}

const recordAnnouncementTerminalReceipt = `-- name: RecordAnnouncementTerminalReceipt :execrows
UPDATE core.pass_registration_announcements SET message_id=$1::bigint
WHERE id=$2::bigint AND bot_id=$3::bigint
 AND attempts=$4::bigint AND last_uncertain_attempt=$4::bigint
 AND state IN ('failed','cancelled') AND lease_until IS NULL
 AND $1::bigint>0
 AND (message_id=0 OR message_id=$1::bigint)
`

type RecordAnnouncementTerminalReceiptParams struct {
	MessageID int64
	ID        int64
	BotID     int64
	Attempt   int64
}

func (q *Queries) RecordAnnouncementTerminalReceipt(ctx context.Context, arg RecordAnnouncementTerminalReceiptParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordAnnouncementTerminalReceipt,
		arg.MessageID,
		arg.ID,
		arg.BotID,
		arg.Attempt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordAnnouncementUncertainty = `-- name: RecordAnnouncementUncertainty :exec
UPDATE core.pass_registration_announcements SET last_uncertain_attempt=$1::bigint,
 last_uncertain_reason=$2::text,last_uncertain_recorded_at=clock_timestamp()
WHERE id=$3::bigint AND bot_id=$4::bigint AND attempts=$1::bigint
 AND (last_uncertain_attempt IS NULL OR last_uncertain_attempt<$1::bigint)
`

type RecordAnnouncementUncertaintyParams struct {
	Attempt int64
	Reason  string
	ID      int64
	BotID   int64
}

func (q *Queries) RecordAnnouncementUncertainty(ctx context.Context, arg RecordAnnouncementUncertaintyParams) error {
	_, err := q.db.Exec(ctx, recordAnnouncementUncertainty,
		arg.Attempt,
		arg.Reason,
		arg.ID,
		arg.BotID,
	)
	return err
}
