// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authority.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const lockReadActor = `-- name: LockReadActor :one
SELECT telegram_id FROM core.users WHERE id=$1 FOR SHARE
`

func (q *Queries) LockReadActor(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRow(ctx, lockReadActor, id)
	var telegram_id int64
	err := row.Scan(&telegram_id)
	return telegram_id, err
}

const lockReadBooking = `-- name: LockReadBooking :one
SELECT owner,version,created_at,state,invitation_target,COALESCE(payment_attempt,'') AS payment_attempt
FROM core.pass_bookings WHERE event_id=$1 AND owner=$2 FOR SHARE
`

type LockReadBookingParams struct {
	EventID string
	Owner   string
}

type LockReadBookingRow struct {
	Owner            string
	Version          int64
	CreatedAt        pgtype.Timestamptz
	State            string
	InvitationTarget int64
	PaymentAttempt   string
}

func (q *Queries) LockReadBooking(ctx context.Context, arg LockReadBookingParams) (LockReadBookingRow, error) {
	row := q.db.QueryRow(ctx, lockReadBooking, arg.EventID, arg.Owner)
	var i LockReadBookingRow
	err := row.Scan(
		&i.Owner,
		&i.Version,
		&i.CreatedAt,
		&i.State,
		&i.InvitationTarget,
		&i.PaymentAttempt,
	)
	return i, err
}

const lockReadEvents = `-- name: LockReadEvents :many
SELECT id FROM core.pass_events WHERE id=ANY($1::text[]) ORDER BY id FOR SHARE
`

func (q *Queries) LockReadEvents(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, lockReadEvents, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockReadPaymentAttempt = `-- name: LockReadPaymentAttempt :one
SELECT decision='pending' AS pending FROM core.pass_payment_attempts WHERE event_id=$1 AND id=$2 FOR SHARE
`

type LockReadPaymentAttemptParams struct {
	EventID string
	ID      string
}

func (q *Queries) LockReadPaymentAttempt(ctx context.Context, arg LockReadPaymentAttemptParams) (bool, error) {
	row := q.db.QueryRow(ctx, lockReadPaymentAttempt, arg.EventID, arg.ID)
	var pending bool
	err := row.Scan(&pending)
	return pending, err
}

const lockReadTarget = `-- name: LockReadTarget :one
SELECT id,can_book FROM core.users WHERE telegram_id=$1 FOR SHARE
`

type LockReadTargetRow struct {
	ID      string
	CanBook bool
}

func (q *Queries) LockReadTarget(ctx context.Context, telegramID int64) (LockReadTargetRow, error) {
	row := q.db.QueryRow(ctx, lockReadTarget, telegramID)
	var i LockReadTargetRow
	err := row.Scan(&i.ID, &i.CanBook)
	return i, err
}
