// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CorePassNotification struct {
	ID                int64
	EventID           string
	Owner             string
	Recipient         string
	Kind              string
	Generation        string
	Payload           []byte
	CreatedAt         pgtype.Timestamptz
	AvailableAt       pgtype.Timestamptz
	DeliveredAt       pgtype.Timestamptz
	Failure           string
	BotID             pgtype.Int8
	DeliveryState     string
	DeliveryChat      int64
	DeliveryAttempt   int64
	LeaseUntil        pgtype.Timestamptz
	TelegramMessageID int64
	DeliveryText      string
	FailureCount      int64
	FollowupPending   bool
	FollowupFailure   string
	FollowupAttempts  int64
}
