// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_delivery.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const beginNotificationSend = `-- name: BeginNotificationSend :one
UPDATE core.pass_notifications SET delivery_wire_payload=COALESCE(delivery_wire_payload,$1::jsonb),delivery_state='sending',lease_until=clock_timestamp()+interval '2 minutes',
 uncertain_resends=uncertain_resends+CASE WHEN last_uncertain_attempt IS NOT NULL THEN 1 ELSE 0 END
WHERE id=$2::bigint AND bot_id=$3::bigint AND delivery_attempt=$4::bigint
AND delivery_state='pending' AND lease_until>clock_timestamp()
AND (last_uncertain_attempt IS NULL OR uncertain_resends<3) RETURNING delivery_wire_payload
`

type BeginNotificationSendParams struct {
	WirePayload []byte
	ID          int64
	BotID       int64
	Attempt     int64
}

func (q *Queries) BeginNotificationSend(ctx context.Context, arg BeginNotificationSendParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, beginNotificationSend,
		arg.WirePayload,
		arg.ID,
		arg.BotID,
		arg.Attempt,
	)
	var delivery_wire_payload []byte
	err := row.Scan(&delivery_wire_payload)
	return delivery_wire_payload, err
}

const enqueueNotification = `-- name: EnqueueNotification :one
INSERT INTO core.pass_notifications(event_id,owner,recipient,kind,generation,payload,bot_id,delivery_chat)
VALUES($1::text,$2::text,$3::text,$4::text,
 $5::text,$6::jsonb,
 CASE WHEN $7::bigint>0 THEN $7::bigint END,COALESCE((SELECT telegram_id FROM core.users WHERE id=$3::text),0)) ON CONFLICT DO NOTHING RETURNING id, event_id, owner, recipient, kind, generation, payload, created_at, available_at, delivered_at, failure, bot_id, delivery_state, delivery_chat, delivery_attempt, lease_until, telegram_message_id, delivery_text, failure_count, followup_pending, followup_failure, followup_attempts, delivery_wire_payload, last_uncertain_attempt, last_confirmed_attempt, last_uncertain_reason, last_uncertain_recorded_at, uncertain_resends
`

type EnqueueNotificationParams struct {
	EventID    string
	Owner      string
	Recipient  string
	Kind       string
	Generation string
	Payload    []byte
	BotID      int64
}

func (q *Queries) EnqueueNotification(ctx context.Context, arg EnqueueNotificationParams) (CorePassNotification, error) {
	row := q.db.QueryRow(ctx, enqueueNotification,
		arg.EventID,
		arg.Owner,
		arg.Recipient,
		arg.Kind,
		arg.Generation,
		arg.Payload,
		arg.BotID,
	)
	var i CorePassNotification
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Owner,
		&i.Recipient,
		&i.Kind,
		&i.Generation,
		&i.Payload,
		&i.CreatedAt,
		&i.AvailableAt,
		&i.DeliveredAt,
		&i.Failure,
		&i.BotID,
		&i.DeliveryState,
		&i.DeliveryChat,
		&i.DeliveryAttempt,
		&i.LeaseUntil,
		&i.TelegramMessageID,
		&i.DeliveryText,
		&i.FailureCount,
		&i.FollowupPending,
		&i.FollowupFailure,
		&i.FollowupAttempts,
		&i.DeliveryWirePayload,
		&i.LastUncertainAttempt,
		&i.LastConfirmedAttempt,
		&i.LastUncertainReason,
		&i.LastUncertainRecordedAt,
		&i.UncertainResends,
	)
	return i, err
}

const expiredNotification = `-- name: ExpiredNotification :one
SELECT id, event_id, owner, recipient, kind, generation, payload, created_at, available_at, delivered_at, failure, bot_id, delivery_state, delivery_chat, delivery_attempt, lease_until, telegram_message_id, delivery_text, failure_count, followup_pending, followup_failure, followup_attempts, delivery_wire_payload, last_uncertain_attempt, last_confirmed_attempt, last_uncertain_reason, last_uncertain_recorded_at, uncertain_resends FROM core.pass_notifications
WHERE bot_id=$1::bigint
AND (delivery_state='unknown' OR (delivery_state='sending' AND lease_until<=clock_timestamp()))
ORDER BY id LIMIT 1
`

func (q *Queries) ExpiredNotification(ctx context.Context, botID int64) (CorePassNotification, error) {
	row := q.db.QueryRow(ctx, expiredNotification, botID)
	var i CorePassNotification
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Owner,
		&i.Recipient,
		&i.Kind,
		&i.Generation,
		&i.Payload,
		&i.CreatedAt,
		&i.AvailableAt,
		&i.DeliveredAt,
		&i.Failure,
		&i.BotID,
		&i.DeliveryState,
		&i.DeliveryChat,
		&i.DeliveryAttempt,
		&i.LeaseUntil,
		&i.TelegramMessageID,
		&i.DeliveryText,
		&i.FailureCount,
		&i.FollowupPending,
		&i.FollowupFailure,
		&i.FollowupAttempts,
		&i.DeliveryWirePayload,
		&i.LastUncertainAttempt,
		&i.LastConfirmedAttempt,
		&i.LastUncertainReason,
		&i.LastUncertainRecordedAt,
		&i.UncertainResends,
	)
	return i, err
}

const finishNotificationDelivery = `-- name: FinishNotificationDelivery :execrows
UPDATE core.pass_notifications SET delivery_state=$1::text,
 last_confirmed_attempt=CASE WHEN $2::boolean THEN delivery_attempt ELSE last_confirmed_attempt END,
 telegram_message_id=$3::bigint,delivery_text=$4::text,failure=$5::text,
 available_at=CASE WHEN last_uncertain_attempt IS NOT NULL AND $1::text='pending'
  THEN GREATEST(available_at,$6::timestamptz) ELSE $6::timestamptz END,
 lease_until=CASE WHEN $1::text='sent' THEN clock_timestamp()+interval '2 minutes' END,
 followup_pending=($1::text='sent'),
 failure_count=failure_count+$7::bigint,
 delivered_at=CASE WHEN $1::text IN ('failed','cancelled') THEN clock_timestamp() END
WHERE id=$8::bigint AND bot_id=$9::bigint AND delivery_attempt=$10::bigint
AND delivery_state IN ('pending','sending','unknown')
`

type FinishNotificationDeliveryParams struct {
	State            string
	Confirmed        bool
	MessageID        int64
	Text             string
	Failure          string
	AvailableAt      pgtype.Timestamptz
	FailureIncrement int64
	ID               int64
	BotID            int64
	Attempt          int64
}

func (q *Queries) FinishNotificationDelivery(ctx context.Context, arg FinishNotificationDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishNotificationDelivery,
		arg.State,
		arg.Confirmed,
		arg.MessageID,
		arg.Text,
		arg.Failure,
		arg.AvailableAt,
		arg.FailureIncrement,
		arg.ID,
		arg.BotID,
		arg.Attempt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishNotificationFollowup = `-- name: FinishNotificationFollowup :execrows
UPDATE core.pass_notifications SET followup_pending=NOT $1::boolean,
 followup_failure=$2::text,followup_attempts=followup_attempts+1,
 available_at=$3::timestamptz,lease_until=NULL,
 delivered_at=CASE WHEN $1::boolean THEN clock_timestamp() END
WHERE id=$4::bigint AND bot_id=$5::bigint AND delivery_attempt=$6::bigint
AND delivery_state='sent' AND followup_pending
`

type FinishNotificationFollowupParams struct {
	Done        bool
	Failure     string
	AvailableAt pgtype.Timestamptz
	ID          int64
	BotID       int64
	Attempt     int64
}

func (q *Queries) FinishNotificationFollowup(ctx context.Context, arg FinishNotificationFollowupParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishNotificationFollowup,
		arg.Done,
		arg.Failure,
		arg.AvailableAt,
		arg.ID,
		arg.BotID,
		arg.Attempt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lockNotificationAttempt = `-- name: LockNotificationAttempt :one
SELECT id, event_id, owner, recipient, kind, generation, payload, created_at, available_at, delivered_at, failure, bot_id, delivery_state, delivery_chat, delivery_attempt, lease_until, telegram_message_id, delivery_text, failure_count, followup_pending, followup_failure, followup_attempts, delivery_wire_payload, last_uncertain_attempt, last_confirmed_attempt, last_uncertain_reason, last_uncertain_recorded_at, uncertain_resends,COALESCE(lease_until>clock_timestamp(),false)::boolean AS lease_live FROM core.pass_notifications
WHERE id=$1::bigint AND bot_id=$2::bigint AND delivery_attempt=$3::bigint FOR UPDATE
`

type LockNotificationAttemptParams struct {
	ID      int64
	BotID   int64
	Attempt int64
}

type LockNotificationAttemptRow struct {
	ID                      int64
	EventID                 string
	Owner                   string
	Recipient               string
	Kind                    string
	Generation              string
	Payload                 []byte
	CreatedAt               pgtype.Timestamptz
	AvailableAt             pgtype.Timestamptz
	DeliveredAt             pgtype.Timestamptz
	Failure                 string
	BotID                   pgtype.Int8
	DeliveryState           string
	DeliveryChat            int64
	DeliveryAttempt         int64
	LeaseUntil              pgtype.Timestamptz
	TelegramMessageID       int64
	DeliveryText            string
	FailureCount            int64
	FollowupPending         bool
	FollowupFailure         string
	FollowupAttempts        int64
	DeliveryWirePayload     []byte
	LastUncertainAttempt    pgtype.Int8
	LastConfirmedAttempt    pgtype.Int8
	LastUncertainReason     pgtype.Text
	LastUncertainRecordedAt pgtype.Timestamptz
	UncertainResends        int64
	LeaseLive               bool
}

func (q *Queries) LockNotificationAttempt(ctx context.Context, arg LockNotificationAttemptParams) (LockNotificationAttemptRow, error) {
	row := q.db.QueryRow(ctx, lockNotificationAttempt, arg.ID, arg.BotID, arg.Attempt)
	var i LockNotificationAttemptRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Owner,
		&i.Recipient,
		&i.Kind,
		&i.Generation,
		&i.Payload,
		&i.CreatedAt,
		&i.AvailableAt,
		&i.DeliveredAt,
		&i.Failure,
		&i.BotID,
		&i.DeliveryState,
		&i.DeliveryChat,
		&i.DeliveryAttempt,
		&i.LeaseUntil,
		&i.TelegramMessageID,
		&i.DeliveryText,
		&i.FailureCount,
		&i.FollowupPending,
		&i.FollowupFailure,
		&i.FollowupAttempts,
		&i.DeliveryWirePayload,
		&i.LastUncertainAttempt,
		&i.LastConfirmedAttempt,
		&i.LastUncertainReason,
		&i.LastUncertainRecordedAt,
		&i.UncertainResends,
		&i.LeaseLive,
	)
	return i, err
}

const lockNotificationEvent = `-- name: LockNotificationEvent :one
SELECT id FROM core.pass_events WHERE id=$1::text FOR NO KEY UPDATE
`

func (q *Queries) LockNotificationEvent(ctx context.Context, event string) (string, error) {
	row := q.db.QueryRow(ctx, lockNotificationEvent, event)
	var id string
	err := row.Scan(&id)
	return id, err
}

const lockNotificationRecipient = `-- name: LockNotificationRecipient :one
SELECT telegram_id,can_book FROM core.users WHERE id=$1::text FOR SHARE
`

type LockNotificationRecipientRow struct {
	TelegramID int64
	CanBook    bool
}

func (q *Queries) LockNotificationRecipient(ctx context.Context, owner string) (LockNotificationRecipientRow, error) {
	row := q.db.QueryRow(ctx, lockNotificationRecipient, owner)
	var i LockNotificationRecipientRow
	err := row.Scan(&i.TelegramID, &i.CanBook)
	return i, err
}

const missingNotificationIndex = `-- name: MissingNotificationIndex :one
SELECT EXISTS(SELECT 1 FROM core.pass_notifications n
WHERE n.bot_id=$1::bigint AND n.delivery_chat<>0
AND (n.delivery_state IN ('pending','sending','unknown','parked','paused') OR n.followup_pending)
AND NOT EXISTS(SELECT 1 FROM core.delivery_queue q WHERE q.bot_id=n.bot_id
 AND q.owner_kind='passes' AND q.owner_key=n.id::text AND q.effect_key='send'))::boolean
`

func (q *Queries) MissingNotificationIndex(ctx context.Context, botID int64) (bool, error) {
	row := q.db.QueryRow(ctx, missingNotificationIndex, botID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const notificationTitles = `-- name: NotificationTitles :one
SELECT titles FROM core.pass_events WHERE id=$1::text
`

func (q *Queries) NotificationTitles(ctx context.Context, event string) ([]byte, error) {
	row := q.db.QueryRow(ctx, notificationTitles, event)
	var titles []byte
	err := row.Scan(&titles)
	return titles, err
}

const pauseUnroutableNotification = `-- name: PauseUnroutableNotification :exec
UPDATE core.pass_notifications SET delivery_state='paused',failure='notification_identity_unavailable'
WHERE id=$1::bigint AND delivery_state='pending' AND (bot_id IS NULL OR delivery_chat=0)
`

func (q *Queries) PauseUnroutableNotification(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, pauseUnroutableNotification, id)
	return err
}

const prepareNotification = `-- name: PrepareNotification :one
WITH head AS (
 SELECT n.id,COALESCE(u.telegram_id,0)::bigint AS chat FROM core.pass_notifications n JOIN core.users u ON u.id=n.recipient
 WHERE n.bot_id=$1::bigint
 AND ($2::bigint=0 OR n.id=$2::bigint)
 AND (NOT $3::boolean OR (n.delivery_state='sent' AND n.followup_pending))
 AND ($4::text='' OR n.recipient=$4::text)
 AND (n.delivery_state='pending' OR (n.delivery_state='sent' AND n.followup_pending))
 AND n.available_at<=clock_timestamp() AND (n.lease_until IS NULL OR n.lease_until<=clock_timestamp())
 AND NOT EXISTS(SELECT 1 FROM core.pass_notifications older
  JOIN core.delivery_queue oq ON oq.bot_id=older.bot_id AND oq.owner_kind='passes'
   AND oq.owner_key=older.id::text AND oq.effect_key='send'
  JOIN core.delivery_queue nq ON nq.bot_id=n.bot_id AND nq.owner_kind='passes'
   AND nq.owner_key=n.id::text AND nq.effect_key='send'
  WHERE older.bot_id=n.bot_id AND older.delivery_chat=n.delivery_chat
   AND older.followup_pending AND oq.lane_sequence<nq.lane_sequence)
 AND (n.delivery_state='sent' OR EXISTS(SELECT 1 FROM core.delivery_queue q
  WHERE q.bot_id=n.bot_id AND q.owner_kind='passes' AND q.owner_key=n.id::text AND q.effect_key='send'
  AND NOT EXISTS(SELECT 1 FROM core.delivery_queue previous WHERE previous.bot_id=q.bot_id
   AND previous.chat=q.chat AND previous.lane_sequence<q.lane_sequence
   AND previous.state IN ('pending','sending','unknown','parked','paused'))))
 ORDER BY n.available_at,n.id LIMIT 1 FOR UPDATE OF n SKIP LOCKED
)
UPDATE core.pass_notifications n SET delivery_attempt=delivery_attempt+CASE
 WHEN delivery_state='pending' AND last_uncertain_attempt IS NOT NULL AND uncertain_resends>=3 THEN 0 ELSE 1 END,
 lease_until=clock_timestamp()+interval '2 minutes'
FROM head WHERE n.id=head.id RETURNING n.id, n.event_id, n.owner, n.recipient, n.kind, n.generation, n.payload, n.created_at, n.available_at, n.delivered_at, n.failure, n.bot_id, n.delivery_state, n.delivery_chat, n.delivery_attempt, n.lease_until, n.telegram_message_id, n.delivery_text, n.failure_count, n.followup_pending, n.followup_failure, n.followup_attempts, n.delivery_wire_payload, n.last_uncertain_attempt, n.last_confirmed_attempt, n.last_uncertain_reason, n.last_uncertain_recorded_at, n.uncertain_resends
`

type PrepareNotificationParams struct {
	BotID        int64
	ID           int64
	FollowupOnly bool
	Owner        string
}

func (q *Queries) PrepareNotification(ctx context.Context, arg PrepareNotificationParams) (CorePassNotification, error) {
	row := q.db.QueryRow(ctx, prepareNotification,
		arg.BotID,
		arg.ID,
		arg.FollowupOnly,
		arg.Owner,
	)
	var i CorePassNotification
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Owner,
		&i.Recipient,
		&i.Kind,
		&i.Generation,
		&i.Payload,
		&i.CreatedAt,
		&i.AvailableAt,
		&i.DeliveredAt,
		&i.Failure,
		&i.BotID,
		&i.DeliveryState,
		&i.DeliveryChat,
		&i.DeliveryAttempt,
		&i.LeaseUntil,
		&i.TelegramMessageID,
		&i.DeliveryText,
		&i.FailureCount,
		&i.FollowupPending,
		&i.FollowupFailure,
		&i.FollowupAttempts,
		&i.DeliveryWirePayload,
		&i.LastUncertainAttempt,
		&i.LastConfirmedAttempt,
		&i.LastUncertainReason,
		&i.LastUncertainRecordedAt,
		&i.UncertainResends,
	)
	return i, err
}

const readNotification = `-- name: ReadNotification :one
SELECT id, event_id, owner, recipient, kind, generation, payload, created_at, available_at, delivered_at, failure, bot_id, delivery_state, delivery_chat, delivery_attempt, lease_until, telegram_message_id, delivery_text, failure_count, followup_pending, followup_failure, followup_attempts, delivery_wire_payload, last_uncertain_attempt, last_confirmed_attempt, last_uncertain_reason, last_uncertain_recorded_at, uncertain_resends FROM core.pass_notifications WHERE id=$1::bigint AND bot_id=$2::bigint
`

type ReadNotificationParams struct {
	ID    int64
	BotID int64
}

func (q *Queries) ReadNotification(ctx context.Context, arg ReadNotificationParams) (CorePassNotification, error) {
	row := q.db.QueryRow(ctx, readNotification, arg.ID, arg.BotID)
	var i CorePassNotification
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Owner,
		&i.Recipient,
		&i.Kind,
		&i.Generation,
		&i.Payload,
		&i.CreatedAt,
		&i.AvailableAt,
		&i.DeliveredAt,
		&i.Failure,
		&i.BotID,
		&i.DeliveryState,
		&i.DeliveryChat,
		&i.DeliveryAttempt,
		&i.LeaseUntil,
		&i.TelegramMessageID,
		&i.DeliveryText,
		&i.FailureCount,
		&i.FollowupPending,
		&i.FollowupFailure,
		&i.FollowupAttempts,
		&i.DeliveryWirePayload,
		&i.LastUncertainAttempt,
		&i.LastConfirmedAttempt,
		&i.LastUncertainReason,
		&i.LastUncertainRecordedAt,
		&i.UncertainResends,
	)
	return i, err
}

const recordNotificationUncertainty = `-- name: RecordNotificationUncertainty :execrows
UPDATE core.pass_notifications SET
 last_uncertain_recorded_at=CASE WHEN last_uncertain_attempt IS DISTINCT FROM delivery_attempt
  THEN clock_timestamp() ELSE last_uncertain_recorded_at END,
 last_uncertain_attempt=delivery_attempt,last_uncertain_reason='telegram_outcome_unknown'
WHERE id=$1::bigint AND bot_id=$2::bigint
 AND delivery_attempt=$3::bigint AND delivery_state IN ('sending','unknown')
`

type RecordNotificationUncertaintyParams struct {
	ID      int64
	BotID   int64
	Attempt int64
}

func (q *Queries) RecordNotificationUncertainty(ctx context.Context, arg RecordNotificationUncertaintyParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordNotificationUncertainty, arg.ID, arg.BotID, arg.Attempt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordTerminalNotificationConfirmation = `-- name: RecordTerminalNotificationConfirmation :execrows
UPDATE core.pass_notifications SET last_confirmed_attempt=delivery_attempt
WHERE id=$1::bigint AND bot_id=$2::bigint
 AND delivery_attempt=$3::bigint AND last_uncertain_attempt=delivery_attempt
 AND delivery_state IN ('failed','cancelled') AND lease_until IS NULL AND telegram_message_id=0
`

type RecordTerminalNotificationConfirmationParams struct {
	ID      int64
	BotID   int64
	Attempt int64
}

func (q *Queries) RecordTerminalNotificationConfirmation(ctx context.Context, arg RecordTerminalNotificationConfirmationParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordTerminalNotificationConfirmation, arg.ID, arg.BotID, arg.Attempt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordTerminalNotificationReceipt = `-- name: RecordTerminalNotificationReceipt :execrows
UPDATE core.pass_notifications SET telegram_message_id=$1::bigint
WHERE id=$2::bigint AND bot_id=$3::bigint
 AND delivery_attempt=$4::bigint AND last_uncertain_attempt=delivery_attempt
 AND delivery_state IN ('failed','cancelled') AND lease_until IS NULL
 AND last_confirmed_attempt IS DISTINCT FROM delivery_attempt
 AND $1::bigint>0 AND telegram_message_id IN (0,$1::bigint)
`

type RecordTerminalNotificationReceiptParams struct {
	MessageID int64
	ID        int64
	BotID     int64
	Attempt   int64
}

func (q *Queries) RecordTerminalNotificationReceipt(ctx context.Context, arg RecordTerminalNotificationReceiptParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordTerminalNotificationReceipt,
		arg.MessageID,
		arg.ID,
		arg.BotID,
		arg.Attempt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rescheduleUncertainNotification = `-- name: RescheduleUncertainNotification :one
WITH retry AS (
 SELECT id,clock_timestamp() AS observed_at,
  GREATEST(available_at,$2::timestamptz,
   clock_timestamp()+$3::bigint *
    CASE uncertain_resends WHEN 0 THEN 1 WHEN 1 THEN 2 ELSE 4 END * interval '1 second') AS next_at,
  uncertain_resends>=3 AND ($1::boolean
   OR $2::timestamptz<=clock_timestamp()) AS exhausted
 FROM core.pass_notifications
 WHERE id=$4::bigint AND bot_id=$5::bigint
  AND delivery_attempt=$6::bigint AND delivery_state IN ('pending','sending','unknown')
  AND ($1::boolean OR last_uncertain_attempt IS NOT NULL)
)
UPDATE core.pass_notifications n SET
 last_uncertain_attempt=CASE WHEN $1::boolean THEN n.delivery_attempt ELSE n.last_uncertain_attempt END,
 last_uncertain_reason=CASE WHEN $1::boolean THEN 'telegram_outcome_unknown' ELSE n.last_uncertain_reason END,
 last_uncertain_recorded_at=CASE WHEN $1::boolean
  AND n.last_uncertain_attempt IS DISTINCT FROM n.delivery_attempt THEN retry.observed_at ELSE n.last_uncertain_recorded_at END,
 delivery_state=CASE WHEN retry.exhausted THEN 'failed'
  WHEN retry.next_at>'9999-12-31T23:59:59.999999Z'::timestamptz THEN 'parked' ELSE 'pending' END,
 failure=CASE WHEN retry.exhausted THEN 'telegram_uncertain_retry_exhausted'
  WHEN retry.next_at>'9999-12-31T23:59:59.999999Z'::timestamptz THEN 'telegram_invalid_cooldown' ELSE n.failure END,
 available_at=CASE WHEN retry.exhausted OR retry.next_at>'9999-12-31T23:59:59.999999Z'::timestamptz
  THEN retry.observed_at ELSE retry.next_at END,
 lease_until=NULL,
 delivered_at=CASE WHEN retry.exhausted THEN retry.observed_at ELSE n.delivered_at END
FROM retry WHERE n.id=retry.id RETURNING n.delivery_state,n.available_at
`

type RescheduleUncertainNotificationParams struct {
	Uncertain        bool
	ProviderDeadline pgtype.Timestamptz
	FallbackSeconds  int64
	ID               int64
	BotID            int64
	Attempt          int64
}

type RescheduleUncertainNotificationRow struct {
	DeliveryState string
	AvailableAt   pgtype.Timestamptz
}

func (q *Queries) RescheduleUncertainNotification(ctx context.Context, arg RescheduleUncertainNotificationParams) (RescheduleUncertainNotificationRow, error) {
	row := q.db.QueryRow(ctx, rescheduleUncertainNotification,
		arg.Uncertain,
		arg.ProviderDeadline,
		arg.FallbackSeconds,
		arg.ID,
		arg.BotID,
		arg.Attempt,
	)
	var i RescheduleUncertainNotificationRow
	err := row.Scan(&i.DeliveryState, &i.AvailableAt)
	return i, err
}
