// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ownership.sql

package dbgen

import (
	"context"
)

const ownsEventBookings = `-- name: OwnsEventBookings :one
SELECT NOT EXISTS (
  SELECT 1 FROM unnest($1::text[]) AS requested(event_id)
  WHERE NOT EXISTS (
    SELECT 1 FROM core.pass_bookings booking
    WHERE booking.event_id=requested.event_id AND booking.owner=$2::text
  )
) AS all_owned
`

type OwnsEventBookingsParams struct {
	Events []string
	Owner  string
}

func (q *Queries) OwnsEventBookings(ctx context.Context, arg OwnsEventBookingsParams) (bool, error) {
	row := q.db.QueryRow(ctx, ownsEventBookings, arg.Events, arg.Owner)
	var all_owned bool
	err := row.Scan(&all_owned)
	return all_owned, err
}
