// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment.sql

package dbgen

import (
	"context"
)

const hasUnsubmittedPayment = `-- name: HasUnsubmittedPayment :one
SELECT EXISTS (
  SELECT 1 FROM core.pass_bookings booking
  WHERE booking.event_id=$1::text AND booking.owner=$2::text
    AND booking.state='assigned' AND booking.payment_attempt IS NULL
    AND NOT EXISTS (
      SELECT 1 FROM core.legacy_pass_payment_metadata metadata
      WHERE metadata.event_id=booking.event_id AND metadata.owner=booking.owner
    )
) AS absent
`

type HasUnsubmittedPaymentParams struct {
	Event string
	Owner string
}

func (q *Queries) HasUnsubmittedPayment(ctx context.Context, arg HasUnsubmittedPaymentParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUnsubmittedPayment, arg.Event, arg.Owner)
	var absent bool
	err := row.Scan(&absent)
	return absent, err
}
