// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registration_retention.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const expiredRegistrationTurns = `-- name: ExpiredRegistrationTurns :many
SELECT id FROM core.registration_intents
WHERE event_id=$1 AND state='captured' AND turn_expires_at<=$2::timestamptz
ORDER BY effective_position,id
`

type ExpiredRegistrationTurnsParams struct {
	EventID    string
	ObservedAt pgtype.Timestamptz
}

func (q *Queries) ExpiredRegistrationTurns(ctx context.Context, arg ExpiredRegistrationTurnsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, expiredRegistrationTurns, arg.EventID, arg.ObservedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const initializeRegistrationTurns = `-- name: InitializeRegistrationTurns :exec
UPDATE core.registration_intents
SET effective_position=COALESCE(effective_position,ingress_id),
 turn_expires_at=checked_at+($1::bigint*interval '1 microsecond')
WHERE event_id=$2 AND origin='canonical_ingress'
 AND state='captured' AND turn_expires_at IS NULL
`

type InitializeRegistrationTurnsParams struct {
	RetentionMicroseconds int64
	EventID               string
}

func (q *Queries) InitializeRegistrationTurns(ctx context.Context, arg InitializeRegistrationTurnsParams) error {
	_, err := q.db.Exec(ctx, initializeRegistrationTurns, arg.RetentionMicroseconds, arg.EventID)
	return err
}

const nativeAdmissionEvidence = `-- name: NativeAdmissionEvidence :one
SELECT received_at,native_outcome FROM core.registration_ingress
WHERE id=$1::bigint AND native_event=$2::text AND native_owner=$3::text
 AND native_payload->'command'->>'key'=$4::text
`

type NativeAdmissionEvidenceParams struct {
	ID    int64
	Event string
	Owner string
	Key   string
}

type NativeAdmissionEvidenceRow struct {
	ReceivedAt    pgtype.Timestamptz
	NativeOutcome string
}

func (q *Queries) NativeAdmissionEvidence(ctx context.Context, arg NativeAdmissionEvidenceParams) (NativeAdmissionEvidenceRow, error) {
	row := q.db.QueryRow(ctx, nativeAdmissionEvidence,
		arg.ID,
		arg.Event,
		arg.Owner,
		arg.Key,
	)
	var i NativeAdmissionEvidenceRow
	err := row.Scan(&i.ReceivedAt, &i.NativeOutcome)
	return i, err
}

const pendingNativeRegistrationRanks = `-- name: PendingNativeRegistrationRanks :many
SELECT g.native_owner::text AS owner,MIN(COALESCE(i.effective_position,g.id))::bigint AS position
FROM core.registration_ingress g
LEFT JOIN core.registration_intents i ON i.event_id=g.native_event AND i.owner=g.native_owner AND i.state<>'cancelled'
WHERE g.native_event=$1::text AND g.native_payload IS NOT NULL AND g.native_outcome=''
 AND (i.id IS NULL OR i.state='captured')
 AND NOT EXISTS(SELECT 1 FROM core.registration_intents retired
  WHERE retired.event_id=g.native_event AND retired.owner=g.native_owner
  AND retired.state='cancelled' AND retired.closed_through_position>=g.id)
GROUP BY g.native_owner
`

type PendingNativeRegistrationRanksRow struct {
	Owner    string
	Position int64
}

func (q *Queries) PendingNativeRegistrationRanks(ctx context.Context, event string) ([]PendingNativeRegistrationRanksRow, error) {
	rows, err := q.db.Query(ctx, pendingNativeRegistrationRanks, event)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingNativeRegistrationRanksRow{}
	for rows.Next() {
		var i PendingNativeRegistrationRanksRow
		if err := rows.Scan(&i.Owner, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registrationRanks = `-- name: RegistrationRanks :many
SELECT owner,COALESCE(effective_position,0)::bigint AS position,state
FROM core.registration_intents WHERE event_id=$1 AND origin='canonical_ingress' AND state<>'cancelled'
`

type RegistrationRanksRow struct {
	Owner    string
	Position int64
	State    string
}

func (q *Queries) RegistrationRanks(ctx context.Context, eventID string) ([]RegistrationRanksRow, error) {
	rows, err := q.db.Query(ctx, registrationRanks, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RegistrationRanksRow{}
	for rows.Next() {
		var i RegistrationRanksRow
		if err := rows.Scan(&i.Owner, &i.Position, &i.State); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateRegistrationTurn = `-- name: RotateRegistrationTurn :exec
UPDATE core.registration_intents
SET effective_position=nextval('core.registration_ingress_id_seq'),
 turn_expires_at=$1::timestamptz,requeue_count=requeue_count+1
WHERE id=$2 AND state='captured' AND turn_expires_at<=$3::timestamptz
`

type RotateRegistrationTurnParams struct {
	Deadline   pgtype.Timestamptz
	ID         int64
	ObservedAt pgtype.Timestamptz
}

func (q *Queries) RotateRegistrationTurn(ctx context.Context, arg RotateRegistrationTurnParams) error {
	_, err := q.db.Exec(ctx, rotateRegistrationTurn, arg.Deadline, arg.ID, arg.ObservedAt)
	return err
}
