package bot

// Stable values shared by persisted delivery references and their producers.
const (
	botFamilyAdminPage          = "admin_page"
	botFamilyAdminExpiry        = "admin_expiry"
	botFamilyAdminPrompt        = "admin_prompt"
	botFamilyAdminFile          = "admin_file"
	botFamilyCredits            = "credits"
	botFamilyKnowledge          = "knowledge"
	botFamilyMassage            = "massage"
	botFamilyFoodReview         = "food_review"
	botFamilyModernOrderExport  = "modern_order_export"
	botFamilyModernOrderProof   = "modern_order_proof"
	botFamilyFoodOrdersExport   = "food_orders_export"
	botFamilyFoodSummaryExport  = "food_summary_export"
	botFamilyFoodProofMeals     = "food_proof_meals"
	botFamilyFoodProofActivity  = "food_proof_activity"
	botFamilyFoodReviewMeals    = "food_review_meals"
	botFamilyFoodReviewActivity = "food_review_activity"
	botPhaseEdit                = "edit"
	botDocumentKind             = "document"
	botReceiptDelivered         = "delivered"
	botFamilyStatic             = "static"
	botFamilyAdminView          = "admin_view"
	botFamilyPassRedaction      = "pass_redaction"
	botFamilyPasses             = "passes"
	botFamilyOrderExport        = "order_export"
	botFamilyOrderProof         = "order_proof"
	botFamilyPassExport         = "pass_export"
	botFamilyPassProof          = "pass_proof"
	botFamilyFoodClosed         = "food_closed"
	botFamilyModelSettings      = "model_settings"
	botPhaseSend                = "send"
	botPassCardReceipt          = "pass_card"
	botRefreshEffect            = "refresh"
)
