// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingress.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertIngress = `-- name: InsertIngress :exec
INSERT INTO core.registration_ingress(kind,bot_id,request_key,telegram_id,native_event,native_owner,native_payload,
 intake_owner,intake_generation,intake_kind,intake_control,intake_digest,intake_message_id,received_at)
VALUES('telegram',$1::bigint,$2::text,$3::bigint,
 $4::text,$5::text,$6::jsonb,
 $7::text,$8::bigint,$9::text,
 $10::text,$11::text,$12::bigint,
 COALESCE($13::timestamptz,clock_timestamp()))
ON CONFLICT DO NOTHING
`

type InsertIngressParams struct {
	BotID            int64
	RequestKey       string
	Sender           int64
	NativeEvent      pgtype.Text
	NativeOwner      pgtype.Text
	NativePayload    []byte
	IntakeOwner      pgtype.Text
	IntakeGeneration pgtype.Int8
	IntakeKind       pgtype.Text
	IntakeControl    pgtype.Text
	IntakeDigest     pgtype.Text
	IntakeMessageID  pgtype.Int8
	ReceivedAt       pgtype.Timestamptz
}

func (q *Queries) InsertIngress(ctx context.Context, arg InsertIngressParams) error {
	_, err := q.db.Exec(ctx, insertIngress,
		arg.BotID,
		arg.RequestKey,
		arg.Sender,
		arg.NativeEvent,
		arg.NativeOwner,
		arg.NativePayload,
		arg.IntakeOwner,
		arg.IntakeGeneration,
		arg.IntakeKind,
		arg.IntakeControl,
		arg.IntakeDigest,
		arg.IntakeMessageID,
		arg.ReceivedAt,
	)
	return err
}
