// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingress.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertIngress = `-- name: InsertIngress :exec
INSERT INTO core.registration_ingress(kind,bot_id,request_key,telegram_id,native_event,native_owner,native_payload,received_at)
VALUES('telegram',$1::bigint,$2::text,$3::bigint,
 $4::text,$5::text,$6::jsonb,
 COALESCE($7::timestamptz,clock_timestamp()))
ON CONFLICT DO NOTHING
`

type InsertIngressParams struct {
	BotID         int64
	RequestKey    string
	Sender        int64
	NativeEvent   pgtype.Text
	NativeOwner   pgtype.Text
	NativePayload []byte
	ReceivedAt    pgtype.Timestamptz
}

func (q *Queries) InsertIngress(ctx context.Context, arg InsertIngressParams) error {
	_, err := q.db.Exec(ctx, insertIngress,
		arg.BotID,
		arg.RequestKey,
		arg.Sender,
		arg.NativeEvent,
		arg.NativeOwner,
		arg.NativePayload,
		arg.ReceivedAt,
	)
	return err
}
