package migrate

import (
	"bufio"
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"io"
	"os"
	"strconv"
)

type EventPlan struct {
	Version        int               `json:"version"`
	ManifestSHA256 string            `json:"manifest_sha256"`
	BotID          int64             `json:"bot_id"`
	Events         []EventPlanRecord `json:"events"`
}

const eventPlanVersion = 2

// EventPlanSummary contains no private event or administrator data.
type EventPlanSummary struct {
	ArtifactSHA256 string `json:"artifact_sha256"`
	Candidates     int64  `json:"candidates"`
	Blocked        int64  `json:"blocked"`
	Reused         bool   `json:"reused"`
}

func PlanEvents(stage, target string, limits Limits) (EventPlanSummary, error) {
	plan, raw, err := preparedEventPlan(stage, limits)
	if err != nil {
		return EventPlanSummary{}, err
	}
	artifact, err := writePrivatePlan(stage, target, func(writer io.Writer) error {
		if _, writeErr := writer.Write(raw); writeErr != nil {
			return errors.New("plan_write_failed")
		}
		return nil
	})
	summary := EventPlanSummary{ArtifactSHA256: artifact.ArtifactSHA256, Reused: artifact.Reused}
	for _, row := range plan.Events {
		if row.Candidate != nil {
			summary.Candidates++
		}
		if len(row.Blockers) > 0 {
			summary.Blocked++
		}
	}
	return summary, err
}

func preparedEventPlan(stage string, limits Limits) (EventPlan, []byte, error) {
	plan := EventPlan{Version: eventPlanVersion, Events: []EventPlanRecord{}}
	if err := limits.validate(); err != nil {
		return plan, nil, err
	}
	root, report, err := verifiedUsersStage(stage, limits)
	if err != nil {
		return plan, nil, err
	}
	defer func() { _ = root.Close() }()
	manifest, err := readVerifiedUsersManifest(root, report, limits)
	if err != nil {
		return plan, nil, err
	}
	if manifest.BotID >= maxTelegramID {
		return plan, nil, errors.New("bot_id_outside_target_range")
	}
	plan.BotID, plan.ManifestSHA256 = manifest.BotID, report.ManifestSHA256
	collection := ""
	for _, source := range manifest.Coverage {
		if source.Domain == eventsSource && source.Status == sourceIncluded {
			collection = source.Name
		}
	}
	if collection == "" {
		return plan, nil, errors.New("events_source_required")
	}
	seen := map[string]bool{}
	budget := &planBudgetWriter{target: io.Discard, remaining: maxUserPlanBytes}
	for _, entry := range manifest.Files {
		if entry.Source != eventsSource {
			continue
		}
		if err = readEventFile(root, entry, collection, limits, seen, &plan, budget); err != nil {
			return plan, nil, err
		}
	}
	var generated bytes.Buffer
	encoder := json.NewEncoder(&planBudgetWriter{target: &generated, remaining: maxUserPlanBytes})
	if encoder.Encode(plan) != nil {
		return plan, nil, errors.New("plan_output_limit")
	}
	return plan, generated.Bytes(), nil
}

func readEventFile(
	root *os.Root,
	entry File,
	collection string,
	limits Limits,
	seen map[string]bool,
	plan *EventPlan,
	budget io.Writer,
) error {
	if entry.Kind != recordsFileKind {
		return errors.New("events_source_requires_records")
	}
	file, err := openRegular(root, entry.Path)
	if err != nil {
		return err
	}
	defer func() { _ = file.Close() }()
	digest := sha256.New()
	bounded := &io.LimitedReader{R: file, N: entry.Bytes + 1}
	scanner := bufio.NewScanner(io.TeeReader(bounded, digest))
	scanner.Buffer(make([]byte, min(recordReadBuffer, limits.RecordBytes+1)), limits.RecordBytes+1)
	var line int64
	encoder := json.NewEncoder(budget)
	for scanner.Scan() {
		line++
		row, parseErr := plannedEvent(scanner.Bytes(), plan.BotID, collection, entry.Path, line)
		if parseErr != nil {
			return parseErr
		}
		if row.Candidate != nil {
			if seen[row.Candidate.ID] {
				return errors.New("duplicate_event_key")
			}
			seen[row.Candidate.ID] = true
		}
		if encoder.Encode(row) != nil {
			return errors.New("plan_output_limit")
		}
		plan.Events = append(plan.Events, row)
	}
	if scanner.Err() != nil || line != entry.Records || bounded.N != 1 ||
		hex.EncodeToString(digest.Sum(nil)) != entry.SHA256 {
		return errors.New("events_source_changed")
	}
	return nil
}

func plannedEvent(data []byte, botID int64, collection, path string, line int64) (EventPlanRecord, error) {
	var record map[string]json.RawMessage
	if validJSON(data) != nil || json.Unmarshal(data, &record) != nil || record == nil {
		return EventPlanRecord{}, errors.New("event_record_invalid")
	}
	id, err := recordID(record["_id"])
	if err != nil {
		return EventPlanRecord{}, errors.New("event_record_id_invalid")
	}
	row := convertEvent(record)
	row.Legacy = UserLegacyReference{
		Key:          identityKey("events:"+strconv.FormatInt(botID, 10)+":"+collection, id),
		Collection:   collection,
		RecordID:     record["_id"],
		File:         path,
		Line:         line,
		RecordSHA256: hashBytes(data),
	}
	return row, nil
}
