package migrate

import (
	"bytes"
	"encoding/json"
	"errors"
	"io"
)

const foodPlanVersion = 1

type FoodPlan struct {
	Version        int               `json:"version"`
	ManifestSHA256 string            `json:"manifest_sha256"`
	BotID          int64             `json:"bot_id"`
	Records        []FoodPlanRecord  `json:"records"`
	Dependencies   []OrderDependency `json:"dependencies"`
	Files          []File            `json:"files"`
	Proofs         []Proof           `json:"proofs"`
	Markers        []FoodPassMarker  `json:"markers"`
}

type FoodPassMarker struct {
	Legacy   UserLegacyReference `json:"legacy"`
	Record   json.RawMessage     `json:"record"`
	Event    string              `json:"event"`
	Owner    int64               `json:"owner"`
	Shadowed bool                `json:"shadowed"`
	First    *bool               `json:"first,omitempty"`
	Last     *bool               `json:"last,omitempty"`
}

type FoodPlanRecord struct {
	Source        string              `json:"source"`
	Legacy        UserLegacyReference `json:"legacy"`
	Record        json.RawMessage     `json:"record"`
	Excluded      bool                `json:"excluded"`
	Blockers      []string            `json:"blockers"`
	Food          *FoodCandidate      `json:"food,omitempty"`
	Configuration *FoodConfiguration  `json:"configuration,omitempty"`
}

type FoodPlanSummary struct {
	ArtifactSHA256 string `json:"artifact_sha256"`
	Records        int64  `json:"records"`
	Blocked        int64  `json:"blocked"`
	Excluded       int64  `json:"excluded"`
	Reused         bool   `json:"reused"`
}

func PlanFood(stage, target string, limits Limits) (FoodPlanSummary, error) {
	plan, raw, err := preparedFoodPlan(stage, limits)
	if err != nil {
		return FoodPlanSummary{}, err
	}
	artifact, err := writePrivatePlan(stage, target, func(writer io.Writer) error {
		_, writeErr := writer.Write(raw)
		return writeErr
	})
	result := FoodPlanSummary{
		ArtifactSHA256: artifact.ArtifactSHA256,
		Records:        int64(len(plan.Records)),
		Reused:         artifact.Reused,
	}
	for _, row := range plan.Records {
		if row.Excluded {
			result.Excluded++
		}
		if len(row.Blockers) > 0 {
			result.Blocked++
		}
	}
	return result, err
}

func preparedFoodPlan(stage string, limits Limits) (FoodPlan, []byte, error) {
	source, _, err := preparedOrderPlan(stage, limits)
	plan := FoodPlan{Version: foodPlanVersion, ManifestSHA256: source.ManifestSHA256, BotID: source.BotID,
		Dependencies: source.Dependencies, Files: source.Files, Proofs: source.Proofs, Records: []FoodPlanRecord{}}
	if err != nil {
		return plan, nil, err
	}
	root, report, err := verifiedUsersStage(stage, limits)
	if err != nil {
		return plan, nil, err
	}
	manifest, err := readVerifiedUsersManifest(root, report, limits)
	_ = root.Close()
	if err != nil {
		return plan, nil, err
	}
	plan.Files = manifest.Files
	for _, original := range source.Records {
		row := FoodPlanRecord{
			Source:   original.Source,
			Legacy:   original.Legacy,
			Record:   original.Record,
			Blockers: []string{},
		}
		row, err = convertFoodPlanRow(row, plan.BotID)
		if err != nil {
			return plan, nil, err
		}
		plan.Records = append(plan.Records, row)
	}
	if err = plan.readPassMarkers(stage, limits); err != nil {
		return plan, nil, err
	}
	var generated bytes.Buffer
	if json.NewEncoder(&planBudgetWriter{target: &generated, remaining: maxUserPlanBytes}).Encode(plan) != nil {
		return plan, nil, errors.New("plan_output_limit")
	}
	return plan, generated.Bytes(), nil
}

func (p *FoodPlan) readPassMarkers(stage string, limits Limits) error {
	passes, _, err := preparedPassPlan(stage, limits)
	if err != nil {
		return err
	}
	p.Markers = []FoodPassMarker{}
	for _, row := range passes.Records {
		if row.Excluded || row.Preferences != nil || row.PassportMarker {
			continue
		}
		var fields map[string]json.RawMessage
		if json.Unmarshal(row.Record, &fields) != nil {
			return errors.New("food_pass_record_invalid")
		}
		raw := row.Record
		if row.Field != "" {
			raw = fields[row.Field]
		}
		var registration map[string]json.RawMessage
		if json.Unmarshal(raw, &registration) != nil {
			return errors.New("food_pass_record_invalid")
		}
		_, first := registration[foodFirstMarker]
		_, last := registration[foodLastMarker]
		if !first && !last {
			continue
		}
		marker, markerErr := foodPassMarker(row, fields, registration, first, last)
		if markerErr != nil {
			return markerErr
		}
		p.Markers = append(p.Markers, marker)
	}
	return nil
}

func foodExcluded(source string, fields map[string]json.RawMessage, bot int64) bool {
	if raw, present := fields["bot_id"]; present {
		value, valid := telegramNumber(raw)
		if valid && value != bot {
			return true
		}
	}
	if source == ordersSource {
		_, present := fields["pass_key"]
		return !present
	}
	if source == orderConfigurationSource {
		var kind string
		_ = json.Unmarshal(fields["kind"], &kind)
		return kind != "legacy_food"
	}
	return true
}

func convertFoodPlanRow(row FoodPlanRecord, bot int64) (FoodPlanRecord, error) {
	var err error
	var fields map[string]json.RawMessage
	if json.Unmarshal(row.Record, &fields) != nil {
		return row, errors.New("food_record_invalid")
	}
	row.Excluded = foodExcluded(row.Source, fields, bot)
	if row.Excluded {
		return row, nil
	}
	{
		if raw, present := fields["bot_id"]; present {
			if _, valid := telegramNumber(raw); !valid {
				row.Blockers = append(row.Blockers, "food_bot_scope_invalid")
			}
		}
		if row.Source == ordersSource {
			row.Food, err = convertFood(row.Record, bot)
		}
		if row.Source == orderConfigurationSource {
			row.Configuration, err = convertFoodConfiguration(row.Record)
		}
		if err != nil {
			row.Blockers = append(row.Blockers, err.Error())
		}
	}
	return row, nil
}

func foodPassMarker(
	row PassPlanRecord,
	fields, registration map[string]json.RawMessage,
	first, last bool,
) (FoodPassMarker, error) {
	var err error
	marker := FoodPassMarker{Legacy: row.Legacy, Record: row.Record, Shadowed: row.Shadowed}
	if row.Field != "" {
		marker.Event = row.Field
		marker.Owner, _ = telegramNumber(fields["user_id"])
	} else {
		marker.Event, err = orderString(registration, "pass_key", true)
		if err != nil {
			return marker, err
		}
		marker.Owner, _ = telegramNumber(registration["user_id"])
	}
	if marker.Owner == 0 || !tokenPattern.MatchString(marker.Event) {
		return marker, errors.New("food_pass_identity_invalid")
	}
	if first {
		marker.First = new(bool)
		if err = foodOptionalBool(registration, foodFirstMarker, marker.First); err != nil {
			return marker, err
		}
	}
	if last {
		marker.Last = new(bool)
		if err = foodOptionalBool(registration, foodLastMarker, marker.Last); err != nil {
			return marker, err
		}
	}
	return marker, nil
}
