package migrate

import (
	"bufio"
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"io"
	"os"
	"strconv"
)

// OrderPlan retains source evidence until catalog, identity and reservation
// prerequisites permit a lossless conversion. It is not an apply artifact.
type OrderPlan struct {
	Version        int                      `json:"version"`
	ManifestSHA256 string                   `json:"manifest_sha256"`
	BotID          int64                    `json:"bot_id"`
	ApplyReady     bool                     `json:"apply_ready"`
	Prerequisites  []string                 `json:"prerequisites"`
	Sources        []Source                 `json:"sources"`
	Files          []File                   `json:"files"`
	Records        []OrderPlanRecord        `json:"records"`
	Dependencies   []OrderDependency        `json:"dependencies"`
	Proofs         []Proof                  `json:"proofs"`
	Dispositions   []OrderDomainDisposition `json:"domain_dispositions,omitempty"`
}

type OrderPlanRecord struct {
	Source          string               `json:"source"`
	Legacy          UserLegacyReference  `json:"legacy"`
	Record          json.RawMessage      `json:"record"`
	Blockers        []string             `json:"blockers"`
	Order           *OrderCandidate      `json:"order,omitempty"`
	Catalog         *OrderCatalog        `json:"catalog,omitempty"`
	Slot            *OrderSlot           `json:"slot,omitempty"`
	DelegatedDomain OrderDelegatedDomain `json:"delegated_domain,omitempty"`
}

// OrderPlanSummary contains counts and digests, never source identifiers.
type OrderPlanSummary struct {
	ArtifactSHA256 string `json:"artifact_sha256"`
	Records        int64  `json:"records"`
	Blocked        int64  `json:"blocked"`
	ApplyReady     bool   `json:"apply_ready"`
	Reused         bool   `json:"reused"`
}

func PlanOrders(stage, target string, limits Limits) (OrderPlanSummary, error) {
	plan, raw, err := preparedOrderPlan(stage, limits)
	if err != nil {
		return OrderPlanSummary{}, err
	}
	artifact, err := writePrivatePlan(stage, target, func(writer io.Writer) error {
		if _, writeErr := writer.Write(raw); writeErr != nil {
			return errors.New("plan_write_failed")
		}
		return nil
	})
	var blocked int64
	for _, row := range plan.Records {
		if len(row.Blockers) > 0 {
			blocked++
		}
	}
	return OrderPlanSummary{ArtifactSHA256: artifact.ArtifactSHA256, Records: int64(len(plan.Records)),
		Blocked: blocked, Reused: artifact.Reused}, err
}

func preparedOrderPlan(stage string, limits Limits) (OrderPlan, []byte, error) {
	plan := OrderPlan{Version: orderPlanVersion, Sources: []Source{}, Files: []File{}, Records: []OrderPlanRecord{},
		Prerequisites: []string{
			"order_catalog_configuration_mapping_required",
			"order_same_bot_owner_links_required",
			"order_payment_proof_mapping_required",
			"order_policy_attestation_required",
		}}
	if err := limits.validate(); err != nil {
		return plan, nil, err
	}
	root, report, err := verifiedUsersStage(stage, limits)
	if err != nil {
		return plan, nil, err
	}
	defer func() { _ = root.Close() }()
	manifest, err := readVerifiedUsersManifest(root, report, limits)
	if err != nil {
		return plan, nil, err
	}
	plan.BotID, plan.ManifestSHA256 = manifest.BotID, report.ManifestSHA256
	if manifest.BotID >= maxTelegramID {
		return plan, nil, errors.New("bot_id_outside_target_range")
	}
	collections := orderPlanCollections(manifest, &plan)
	for _, proof := range manifest.Proofs {
		if proof.Source == ordersSource {
			plan.Proofs = append(plan.Proofs, proof)
		}
	}
	if collections[ordersSource] == "" {
		return plan, nil, errors.New("orders_source_required")
	}
	if err = readOrderPlanInputs(root, manifest, collections, limits, &plan); err != nil {
		return plan, nil, err
	}
	plan.recordDomainDispositions(manifest)
	var generated bytes.Buffer
	if json.NewEncoder(&planBudgetWriter{target: &generated, remaining: maxUserPlanBytes}).Encode(plan) != nil {
		return plan, nil, errors.New("plan_output_limit")
	}
	return plan, generated.Bytes(), nil
}

func orderPlanCollections(manifest Manifest, plan *OrderPlan) map[string]string {
	collections := map[string]string{}
	for _, source := range manifest.Coverage {
		if !orderPlanSource(source.Domain) {
			continue
		}
		plan.Sources = append(plan.Sources, source)
		if source.Status == sourceIncluded {
			collections[source.Domain] = source.Name
		}
	}
	return collections
}

func orderPlanSource(source string) bool {
	return source == ordersSource || source == "order_capacity" || source == orderConfigurationSource
}

func readOrderPlanFile(
	root *os.Root,
	entry File,
	collection string,
	limits Limits,
	plan *OrderPlan,
	budget io.Writer,
) error {
	file, err := openRegular(root, entry.Path)
	if err != nil {
		return err
	}
	defer func() { _ = file.Close() }()
	digest := sha256.New()
	bounded := &io.LimitedReader{R: file, N: entry.Bytes + 1}
	scanner := bufio.NewScanner(io.TeeReader(bounded, digest))
	scanner.Buffer(make([]byte, min(recordReadBuffer, limits.RecordBytes+1)), limits.RecordBytes+1)
	var line int64
	encoder := json.NewEncoder(budget)
	for scanner.Scan() {
		line++
		row, parseErr := plannedOrderRecord(scanner.Bytes(), entry, collection, plan.BotID, line)
		if parseErr != nil {
			return parseErr
		}
		if encoder.Encode(row) != nil {
			return errors.New("plan_output_limit")
		}
		plan.Records = append(plan.Records, row)
	}
	if scanner.Err() != nil || line != entry.Records || bounded.N != 1 ||
		hex.EncodeToString(digest.Sum(nil)) != entry.SHA256 {
		return errors.New("orders_source_changed")
	}
	return nil
}

func plannedOrderRecord(data []byte, entry File, collection string, botID, line int64) (OrderPlanRecord, error) {
	var fields map[string]json.RawMessage
	if validJSON(data) != nil || json.Unmarshal(data, &fields) != nil || fields == nil {
		return OrderPlanRecord{}, errors.New("order_record_invalid")
	}
	id, err := recordID(fields["_id"])
	if err != nil {
		return OrderPlanRecord{}, errors.New("order_record_id_invalid")
	}
	row := OrderPlanRecord{
		Source:   entry.Source,
		Record:   bytes.Clone(data),
		Blockers: []string{},
		Legacy: UserLegacyReference{
			Key: identityKey(entry.Source+":"+strconv.FormatInt(botID, 10)+":"+collection, id), Collection: collection,
			RecordID: fields["_id"], File: entry.Path, Line: line, RecordSHA256: hashBytes(data),
		},
	}
	if domain := delegatedOrderRecord(row, fields, botID); domain != "" {
		row.DelegatedDomain = domain
		return row, nil
	}
	if entry.Source == ordersSource {
		row.Order, err = convertOrder(data, botID)
		if _, present := fields["pass_key"]; present {
			err = errors.New("legacy_food_mapping_required")
		}
	}
	if entry.Source == "order_capacity" {
		row.Slot, err = convertOrderSlot(data, botID)
	}
	if entry.Source == orderConfigurationSource {
		row.Catalog, err = convertOrderCatalog(data)
	}
	if err != nil {
		row.Blockers = append(row.Blockers, err.Error())
	}
	return row, nil
}

func readOrderPlanInputs(
	root *os.Root,
	manifest Manifest,
	collections map[string]string,
	limits Limits,
	plan *OrderPlan,
) error {
	var err error
	budget := &planBudgetWriter{target: io.Discard, remaining: maxUserPlanBytes}
	for _, entry := range manifest.Files {
		if entry.Source == usersSource || entry.Source == eventsSource {
			if err = readOrderDependencies(root, entry, manifest, limits, plan, budget); err != nil {
				return err
			}
			continue
		}
		if !orderPlanSource(entry.Source) {
			continue
		}
		plan.Files = append(plan.Files, entry)
		if entry.Kind == orderBlobKind {
			continue
		}
		if entry.Kind != recordsFileKind {
			if entry.Source != orderConfigurationSource {
				return errors.New("orders_source_requires_records")
			}
			continue
		}
		if err = readOrderPlanFile(root, entry, collections[entry.Source], limits, plan, budget); err != nil {
			return err
		}
	}
	return nil
}
