package migrate

import (
	"bufio"
	"bytes"
	"encoding/json"
	"errors"
	"io"
	"net/url"
	"path/filepath"
	"strings"
	"unicode"
)

const maxUserResolutionBytes = 16 << 20

// UserResolution is an explicit operator-attested link, never an email match.
type UserResolution struct {
	LegacyKey string `json:"legacy_key"`
	Owner     string `json:"owner"`
	Issuer    string `json:"issuer"`
	Subject   string `json:"subject"`
	CanBook   *bool  `json:"can_book"`
}

type UserResolutions struct {
	Version          int              `json:"version"`
	PlanSHA256       string           `json:"plan_sha256"`
	IdentityAttested bool             `json:"identity_attested"`
	Users            []UserResolution `json:"users"`
}

type preparedUser struct {
	record     UserPlanRecord
	resolution UserResolution
}

type preparedUsers struct {
	planHash       string
	resolutionHash string
	botID          int64
	excluded       int64
	users          []preparedUser
}

func prepareUsers(stage, plan, resolutions string, limits Limits) (preparedUsers, error) {
	prepared, original, err := verifiedUserPlan(stage, plan, limits)
	if err != nil {
		return prepared, err
	}
	return resolvePreparedUsers(prepared, original, resolutions)
}

func verifiedUserPlan(stage, plan string, limits Limits) (preparedUsers, []byte, error) {
	var prepared preparedUsers
	if err := limits.validate(); err != nil {
		return prepared, nil, err
	}
	root, report, err := verifiedUsersStage(stage, limits)
	if err != nil {
		return prepared, nil, err
	}
	defer func() { _ = root.Close() }()
	manifest, err := readVerifiedUsersManifest(root, report, limits)
	if err != nil {
		return prepared, nil, err
	}
	if manifest.BotID >= maxTelegramID {
		return prepared, nil, errors.New("bot_id_outside_target_range")
	}
	included := false
	for _, source := range manifest.Coverage {
		if source.Domain == usersSource && source.Status == sourceIncluded {
			included = true
		}
	}
	if !included {
		return prepared, nil, errors.New("users_source_required")
	}
	var generated bytes.Buffer
	summary, err := emitUsersPlan(
		&planBudgetWriter{target: &generated, remaining: maxUserPlanBytes},
		root,
		manifest,
		report,
		limits,
	)
	if err != nil {
		return prepared, nil, err
	}
	original, err := readApplyFile(plan, maxUserPlanBytes)
	if err != nil {
		return prepared, nil, err
	}
	if !bytes.Equal(original, generated.Bytes()) {
		return prepared, nil, errors.New("apply_plan_mismatch")
	}
	prepared.planHash = hashBytes(original)
	prepared.botID = manifest.BotID
	prepared.excluded = summary.Excluded
	return prepared, original, nil
}

func resolvePreparedUsers(prepared preparedUsers, original []byte, resolutions string) (preparedUsers, error) {
	raw, err := readApplyFile(resolutions, maxUserResolutionBytes)
	if err != nil {
		return prepared, err
	}
	resolved, err := decodeUserResolutions(raw)
	if err != nil {
		return prepared, err
	}
	if resolved.PlanSHA256 != prepared.planHash {
		return prepared, errors.New("resolution_plan_mismatch")
	}
	prepared.resolutionHash = hashBytes(raw)
	byKey := make(map[string]UserResolution, len(resolved.Users))
	for _, link := range resolved.Users {
		byKey[link.LegacyKey] = link
	}
	scanner := bufio.NewScanner(bytes.NewReader(original))
	scanner.Buffer(make([]byte, recordReadBuffer), maxUserPlanBytes)
	for scanner.Scan() {
		var row UserPlanRecord
		if json.Unmarshal(scanner.Bytes(), &row) != nil {
			return prepared, errors.New("apply_plan_invalid")
		}
		if row.Kind != identityUserRecord || row.Status == userExcluded {
			continue
		}
		if !resolvableUser(row) {
			return prepared, errors.New("apply_record_blocked")
		}
		link, ok := byKey[row.Legacy.Key]
		if !ok {
			return prepared, errors.New("resolution_missing")
		}
		delete(byKey, row.Legacy.Key)
		prepared.users = append(prepared.users, preparedUser{record: row, resolution: link})
	}
	if scanner.Err() != nil {
		return prepared, errors.New("apply_plan_invalid")
	}
	if len(byKey) != 0 {
		return prepared, errors.New("resolution_extra")
	}
	return prepared, nil
}

func resolvableUser(row UserPlanRecord) bool {
	if row.Status != userCandidate || row.Candidate == nil {
		return false
	}
	for _, blocker := range row.Blockers {
		if blocker != "target_identity_unresolved" && blocker != "eligibility_policy_unresolved" {
			return false
		}
	}
	return true
}

func readApplyFile(path string, limit int64) ([]byte, error) {
	absolute, err := filepath.Abs(path)
	if err != nil {
		return nil, errors.New("apply_input_unavailable")
	}
	root, err := openDirectory(filepath.Dir(absolute))
	if err != nil {
		return nil, errors.New("apply_input_unavailable")
	}
	defer func() { _ = root.Close() }()
	file, err := openRegular(root, filepath.Base(absolute))
	if err != nil {
		return nil, errors.New("apply_input_unavailable")
	}
	defer func() { _ = file.Close() }()
	data, err := io.ReadAll(io.LimitReader(file, limit+1))
	if err != nil || int64(len(data)) > limit {
		return nil, errors.New("apply_input_limit")
	}
	return data, nil
}

func decodeUserResolutions(raw []byte) (UserResolutions, error) {
	var result UserResolutions
	if validJSON(raw) != nil {
		return result, errors.New("resolution_invalid")
	}
	fields, err := objectFields(raw, "version plan_sha256 identity_attested users")
	if err != nil {
		return result, errors.New("resolution_invalid")
	}
	var rows []json.RawMessage
	if json.Unmarshal(fields["users"], &rows) != nil {
		return result, errors.New("resolution_invalid")
	}
	for _, row := range rows {
		if _, err = objectFields(row, "legacy_key owner issuer subject can_book"); err != nil {
			return result, errors.New("resolution_invalid")
		}
	}
	if json.Unmarshal(raw, &result) != nil || result.Version != 1 || !result.IdentityAttested {
		return result, errors.New("resolution_attestation_required")
	}
	keys, owners, subjects := map[string]bool{}, map[string]bool{}, map[string]bool{}
	for _, link := range result.Users {
		issuer, parseErr := url.Parse(link.Issuer)
		if len(link.LegacyKey) != 64 || strings.Trim(link.LegacyKey, "0123456789abcdef") != "" ||
			!validLinkText(link.Owner) ||
			!validLinkText(link.Subject) ||
			!validLinkText(link.Issuer) ||
			parseErr != nil ||
			issuer.Scheme != "https" ||
			issuer.Host == "" ||
			issuer.User != nil ||
			issuer.RawQuery != "" ||
			issuer.Fragment != "" ||
			link.CanBook == nil {
			return result, errors.New("resolution_invalid")
		}
		subjectKey := link.Issuer + "\x00" + link.Subject
		if keys[link.LegacyKey] || owners[link.Owner] || subjects[subjectKey] {
			return result, errors.New("resolution_duplicate")
		}
		keys[link.LegacyKey], owners[link.Owner], subjects[subjectKey] = true, true, true
	}
	return result, nil
}

func validLinkText(value string) bool {
	return value != "" && len(value) <= 1024 && strings.TrimSpace(value) == value &&
		!strings.ContainsFunc(value, func(r rune) bool { return unicode.IsControl(r) || r == unicode.ReplacementChar })
}
