// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

type InteractionSavedTurn struct {
	Owner             string
	UpdateID          int64
	Kind              string
	State             string
	Reason            string
	HistoryGeneration int64
	Payload           []byte
}
