// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: turns.sql

package dbgen

import (
	"context"
)

const clearDerivedReplies = `-- name: ClearDerivedReplies :exec
UPDATE bot.interactions AS target SET content='""'::jsonb,native_markdown=false
WHERE target.owner=$1 AND target.update_id=$2 AND target.kind IN ('reply','orders_reply','knowledge_reply','profile_answer','registration_reply')
AND NOT EXISTS(SELECT 1 FROM bot.interactions origin WHERE origin.owner=$1 AND origin.update_id=$2
 AND origin.kind='reply_origin' AND origin.content='"authoritative"'::jsonb)
`

type ClearDerivedRepliesParams struct {
	Owner    string
	UpdateID int64
}

func (q *Queries) ClearDerivedReplies(ctx context.Context, arg ClearDerivedRepliesParams) error {
	_, err := q.db.Exec(ctx, clearDerivedReplies, arg.Owner, arg.UpdateID)
	return err
}

const consumedVoice = `-- name: ConsumedVoice :one
SELECT r.payload,r.kind,r.state,r.reason,r.history_generation,
EXISTS(SELECT 1 FROM bot.media_intake m
WHERE m.owner=r.owner AND m.id=$2 AND m.update_id=r.update_id AND m.av_kind='voice'
AND r.payload->>'media_id'=m.id AND r.payload->'av_ids' ? m.id
AND (m.status='new' OR (m.status='done' AND m.last_action='answer'))
AND (r.payload->'plan'->>'view'<>'media' OR r.payload->'plan'->'media_action'->>'media_id'<>m.id))::boolean AS consumed
FROM interaction.saved_turns r WHERE r.owner=$1 AND r.update_id=$3
`

type ConsumedVoiceParams struct {
	Owner    string
	ID       string
	UpdateID int64
}

type ConsumedVoiceRow struct {
	Payload           []byte
	Kind              string
	State             string
	Reason            string
	HistoryGeneration int64
	Consumed          bool
}

func (q *Queries) ConsumedVoice(ctx context.Context, arg ConsumedVoiceParams) (ConsumedVoiceRow, error) {
	row := q.db.QueryRow(ctx, consumedVoice, arg.Owner, arg.ID, arg.UpdateID)
	var i ConsumedVoiceRow
	err := row.Scan(
		&i.Payload,
		&i.Kind,
		&i.State,
		&i.Reason,
		&i.HistoryGeneration,
		&i.Consumed,
	)
	return i, err
}

const deleteDerivedReplies = `-- name: DeleteDerivedReplies :exec
DELETE FROM bot.interactions AS target WHERE target.owner=$1 AND target.update_id=$2
AND target.kind IN ('reply','orders_reply','knowledge_reply','profile_reply','profile_answer','registration_reply')
AND NOT EXISTS(SELECT 1 FROM bot.interactions origin WHERE origin.owner=$1 AND origin.update_id=$2
 AND origin.kind='reply_origin' AND origin.content='"authoritative"'::jsonb)
`

type DeleteDerivedRepliesParams struct {
	Owner    string
	UpdateID int64
}

func (q *Queries) DeleteDerivedReplies(ctx context.Context, arg DeleteDerivedRepliesParams) error {
	_, err := q.db.Exec(ctx, deleteDerivedReplies, arg.Owner, arg.UpdateID)
	return err
}

const insertTerminalReply = `-- name: InsertTerminalReply :exec
INSERT INTO bot.interactions(owner,update_id,kind,content)
VALUES($1,$2,'reply','""'::jsonb) ON CONFLICT DO NOTHING
`

type InsertTerminalReplyParams struct {
	Owner    string
	UpdateID int64
}

func (q *Queries) InsertTerminalReply(ctx context.Context, arg InsertTerminalReplyParams) error {
	_, err := q.db.Exec(ctx, insertTerminalReply, arg.Owner, arg.UpdateID)
	return err
}

const latestNotice = `-- name: LatestNotice :one
SELECT i.content,i.native_markdown,i.update_id,t.payload,
COALESCE(t.kind,'')::text AS kind, COALESCE(t.state,'')::text AS state,
COALESCE(t.reason,'')::text AS reason, COALESCE(t.history_generation,0)::bigint AS history_generation,
EXISTS(SELECT 1 FROM bot.interactions origin WHERE origin.owner=i.owner AND origin.update_id=i.update_id
 AND origin.kind='reply_origin' AND origin.content='"authoritative"'::jsonb)::boolean AS trusted
FROM bot.interactions i LEFT JOIN interaction.saved_turns t ON t.owner=i.owner AND t.update_id=i.update_id
WHERE i.owner=$1 AND i.kind='reply' ORDER BY i.id DESC LIMIT 1
`

type LatestNoticeRow struct {
	Content           []byte
	NativeMarkdown    bool
	UpdateID          int64
	Payload           []byte
	Kind              string
	State             string
	Reason            string
	HistoryGeneration int64
	Trusted           bool
}

func (q *Queries) LatestNotice(ctx context.Context, owner string) (LatestNoticeRow, error) {
	row := q.db.QueryRow(ctx, latestNotice, owner)
	var i LatestNoticeRow
	err := row.Scan(
		&i.Content,
		&i.NativeMarkdown,
		&i.UpdateID,
		&i.Payload,
		&i.Kind,
		&i.State,
		&i.Reason,
		&i.HistoryGeneration,
		&i.Trusted,
	)
	return i, err
}

const loadTurn = `-- name: LoadTurn :one
SELECT owner, update_id, kind, state, reason, history_generation, payload FROM interaction.saved_turns WHERE owner=$1 AND update_id=$2
`

type LoadTurnParams struct {
	Owner    string
	UpdateID int64
}

func (q *Queries) LoadTurn(ctx context.Context, arg LoadTurnParams) (InteractionSavedTurn, error) {
	row := q.db.QueryRow(ctx, loadTurn, arg.Owner, arg.UpdateID)
	var i InteractionSavedTurn
	err := row.Scan(
		&i.Owner,
		&i.UpdateID,
		&i.Kind,
		&i.State,
		&i.Reason,
		&i.HistoryGeneration,
		&i.Payload,
	)
	return i, err
}

const markTerminal = `-- name: MarkTerminal :execrows
INSERT INTO interaction.saved_turns(owner,update_id,payload,kind,state,reason,history_generation)
VALUES($1,$2,$3,'terminal','privacy_terminal',$4,$5) ON CONFLICT(owner,update_id) DO UPDATE
SET payload=excluded.payload,kind=excluded.kind,state=excluded.state,reason=excluded.reason,history_generation=excluded.history_generation
WHERE interaction.saved_turns.payload->'format_version'='1'::jsonb
`

type MarkTerminalParams struct {
	Owner             string
	UpdateID          int64
	Payload           []byte
	Reason            string
	HistoryGeneration int64
}

func (q *Queries) MarkTerminal(ctx context.Context, arg MarkTerminalParams) (int64, error) {
	result, err := q.db.Exec(ctx, markTerminal,
		arg.Owner,
		arg.UpdateID,
		arg.Payload,
		arg.Reason,
		arg.HistoryGeneration,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const replyOrigin = `-- name: ReplyOrigin :one
SELECT (content#>>'{}')::text AS origin FROM bot.interactions WHERE owner=$1 AND update_id=$2 AND kind='reply_origin'
`

type ReplyOriginParams struct {
	Owner    string
	UpdateID int64
}

func (q *Queries) ReplyOrigin(ctx context.Context, arg ReplyOriginParams) (string, error) {
	row := q.db.QueryRow(ctx, replyOrigin, arg.Owner, arg.UpdateID)
	var origin string
	err := row.Scan(&origin)
	return origin, err
}

const saveTurnWinner = `-- name: SaveTurnWinner :one
INSERT INTO interaction.saved_turns(owner,update_id,payload,kind,state,reason,history_generation)
VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(owner,update_id) DO UPDATE SET payload=interaction.saved_turns.payload
RETURNING owner, update_id, kind, state, reason, history_generation, payload
`

type SaveTurnWinnerParams struct {
	Owner             string
	UpdateID          int64
	Payload           []byte
	Kind              string
	State             string
	Reason            string
	HistoryGeneration int64
}

func (q *Queries) SaveTurnWinner(ctx context.Context, arg SaveTurnWinnerParams) (InteractionSavedTurn, error) {
	row := q.db.QueryRow(ctx, saveTurnWinner,
		arg.Owner,
		arg.UpdateID,
		arg.Payload,
		arg.Kind,
		arg.State,
		arg.Reason,
		arg.HistoryGeneration,
	)
	var i InteractionSavedTurn
	err := row.Scan(
		&i.Owner,
		&i.UpdateID,
		&i.Kind,
		&i.State,
		&i.Reason,
		&i.HistoryGeneration,
		&i.Payload,
	)
	return i, err
}
