CREATE ROLE zns_app LOGIN PASSWORD 'sandbox-product-only';
CREATE ROLE zns_meter LOGIN PASSWORD 'sandbox-meter-only';
CREATE SCHEMA core AUTHORIZATION zns_app;
CREATE SCHEMA bot AUTHORIZATION zns_app;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA core GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO zns_app;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA core GRANT USAGE,SELECT ON SEQUENCES TO zns_app;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA bot GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO zns_app;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA bot GRANT USAGE,SELECT ON SEQUENCES TO zns_app;
