CREATE ROLE zns_api LOGIN PASSWORD 'sandbox-api-only';
CREATE ROLE zns_bot LOGIN PASSWORD 'sandbox-bot-only';
CREATE ROLE zns_meter LOGIN PASSWORD 'sandbox-meter-only';
CREATE SCHEMA core AUTHORIZATION zns_api;
CREATE SCHEMA bot AUTHORIZATION zns_bot;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA core GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO zns_api;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA core GRANT USAGE,SELECT ON SEQUENCES TO zns_api;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA bot GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO zns_bot;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA bot GRANT USAGE,SELECT ON SEQUENCES TO zns_bot;
