// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authority.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"
)

const authorityBatchIDs = `-- name: AuthorityBatchIDs :many
SELECT id FROM core.conversation_events WHERE owner=$1 AND id<$2 AND summarized_version=0
AND NOT EXISTS(SELECT 1 FROM core.conversation_message_bodies b WHERE b.event_id=conversation_events.id)
ORDER BY id LIMIT $3
`

type AuthorityBatchIDsParams struct {
	Owner string
	ID    int64
	Limit int32
}

func (q *Queries) AuthorityBatchIDs(ctx context.Context, arg AuthorityBatchIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, authorityBatchIDs, arg.Owner, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const authorityPageIDs = `-- name: AuthorityPageIDs :many
SELECT id FROM core.conversation_events WHERE owner=$1
AND ($2::bigint=0 OR id<$2) AND id>$3::bigint
ORDER BY id DESC LIMIT $4::bigint
`

type AuthorityPageIDsParams struct {
	Owner     string
	BeforeID  int64
	AfterID   int64
	PageLimit int64
}

func (q *Queries) AuthorityPageIDs(ctx context.Context, arg AuthorityPageIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, authorityPageIDs,
		arg.Owner,
		arg.BeforeID,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasUnprovenRuntimeSummary = `-- name: HasUnprovenRuntimeSummary :one
SELECT EXISTS(SELECT 1 FROM core.conversation_unproven_runtime WHERE owner=$1 AND summarized_version>0)
`

func (q *Queries) HasUnprovenRuntimeSummary(ctx context.Context, owner string) (bool, error) {
	row := q.db.QueryRow(ctx, hasUnprovenRuntimeSummary, owner)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const readAuthorities = `-- name: ReadAuthorities :many
SELECT a.event_id,a.authorities,a.history_generation FROM core.conversation_read_authorities a
JOIN core.conversation_events e ON e.id=a.event_id
WHERE e.owner=$1 AND e.id=ANY($2::bigint[]) AND NOT e.omitted ORDER BY a.event_id
`

type ReadAuthoritiesParams struct {
	Owner   string
	Column2 []int64
}

func (q *Queries) ReadAuthorities(ctx context.Context, arg ReadAuthoritiesParams) ([]CoreConversationReadAuthority, error) {
	rows, err := q.db.Query(ctx, readAuthorities, arg.Owner, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreConversationReadAuthority{}
	for rows.Next() {
		var i CoreConversationReadAuthority
		if err := rows.Scan(&i.EventID, &i.Authorities, &i.HistoryGeneration); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readSummaryAuthorities = `-- name: ReadSummaryAuthorities :one
SELECT read_authorities FROM core.conversation_summaries WHERE owner=$1
`

func (q *Queries) ReadSummaryAuthorities(ctx context.Context, owner string) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, readSummaryAuthorities, owner)
	var read_authorities json.RawMessage
	err := row.Scan(&read_authorities)
	return read_authorities, err
}

const summaryEventsByIDs = `-- name: SummaryEventsByIDs :many
SELECT id,kind,text,details,omitted,created_at,
EXISTS(SELECT 1 FROM core.conversation_message_bodies b WHERE b.event_id=conversation_events.id) AS has_full_text,omission_reason
FROM core.conversation_events WHERE owner=$1 AND id=ANY($2::bigint[]) ORDER BY id
`

type SummaryEventsByIDsParams struct {
	Owner   string
	Column2 []int64
}

type SummaryEventsByIDsRow struct {
	ID             int64
	Kind           string
	Text           string
	Details        json.RawMessage
	Omitted        bool
	At             time.Time
	HasFullText    bool
	OmissionReason string
}

func (q *Queries) SummaryEventsByIDs(ctx context.Context, arg SummaryEventsByIDsParams) ([]SummaryEventsByIDsRow, error) {
	rows, err := q.db.Query(ctx, summaryEventsByIDs, arg.Owner, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SummaryEventsByIDsRow{}
	for rows.Next() {
		var i SummaryEventsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Text,
			&i.Details,
			&i.Omitted,
			&i.At,
			&i.HasFullText,
			&i.OmissionReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unprovenRuntimeIDs = `-- name: UnprovenRuntimeIDs :many
SELECT id FROM core.conversation_unproven_runtime WHERE owner=$1 AND id=ANY($2::bigint[])
`

type UnprovenRuntimeIDsParams struct {
	Owner   string
	Column2 []int64
}

func (q *Queries) UnprovenRuntimeIDs(ctx context.Context, arg UnprovenRuntimeIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, unprovenRuntimeIDs, arg.Owner, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
