// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"encoding/json"
)

type CoreConversationReadAuthority struct {
	EventID           int64
	Authorities       json.RawMessage
	HistoryGeneration int64
}
