// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: read.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"
)

const hasSummaryGap = `-- name: HasSummaryGap :one
SELECT EXISTS(SELECT 1 FROM core.conversation_events
  WHERE owner = $1 AND id < $2 AND summarized_version = 0)
`

type HasSummaryGapParams struct {
	Owner string
	ID    int64
}

func (q *Queries) HasSummaryGap(ctx context.Context, arg HasSummaryGapParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasSummaryGap, arg.Owner, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const historyGeneration = `-- name: HistoryGeneration :one
SELECT COALESCE((SELECT generation FROM core.conversation_history_generations WHERE owner=$1),0)::bigint AS generation
`

func (q *Queries) HistoryGeneration(ctx context.Context, owner string) (int64, error) {
	row := q.db.QueryRow(ctx, historyGeneration, owner)
	var generation int64
	err := row.Scan(&generation)
	return generation, err
}

const historyReadWithinBudget = `-- name: HistoryReadWithinBudget :one
SELECT (
 COALESCE((SELECT sum(
  CASE WHEN $1::boolean THEN 0 ELSE
   octet_length(e.text)::bigint+octet_length(e.details::text)+octet_length(e.omission_reason) END
  +CASE WHEN e.omitted THEN 0 ELSE COALESCE(octet_length(a.authorities::text),0) END)
 FROM core.conversation_events e
 LEFT JOIN core.conversation_read_authorities a ON a.event_id=e.id
 WHERE e.owner=$2 AND e.id=ANY($3::bigint[])),0)
 +CASE WHEN $4::boolean THEN
  COALESCE((SELECT octet_length(text)::bigint+octet_length(read_authorities::text)
   FROM core.conversation_summaries WHERE owner=$2),0)
 ELSE 0 END
) <= $5::bigint AS allowed
`

type HistoryReadWithinBudgetParams struct {
	TextOnly       bool
	Owner          string
	EventIds       []int64
	IncludeSummary bool
	Budget         int64
}

func (q *Queries) HistoryReadWithinBudget(ctx context.Context, arg HistoryReadWithinBudgetParams) (bool, error) {
	row := q.db.QueryRow(ctx, historyReadWithinBudget,
		arg.TextOnly,
		arg.Owner,
		arg.EventIds,
		arg.IncludeSummary,
		arg.Budget,
	)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const knownActor = `-- name: KnownActor :one
SELECT EXISTS(SELECT 1 FROM core.users WHERE id = $1)
`

func (q *Queries) KnownActor(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, knownActor, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const readEvents = `-- name: ReadEvents :many
SELECT id, kind, text, details, omitted, created_at, EXISTS(SELECT 1 FROM core.conversation_message_bodies b WHERE b.event_id=conversation_events.id) AS has_full_text, omission_reason
FROM core.conversation_events
WHERE owner = $1
  AND ($2::bigint = 0 OR id < $2)
  AND id > $3
ORDER BY id DESC
LIMIT $4::bigint
`

type ReadEventsParams struct {
	Owner     string
	BeforeID  int64
	AfterID   int64
	PageLimit int64
}

type ReadEventsRow struct {
	ID             int64
	Kind           string
	Text           string
	Details        json.RawMessage
	Omitted        bool
	At             time.Time
	HasFullText    bool
	OmissionReason string
}

func (q *Queries) ReadEvents(ctx context.Context, arg ReadEventsParams) ([]ReadEventsRow, error) {
	rows, err := q.db.Query(ctx, readEvents,
		arg.Owner,
		arg.BeforeID,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadEventsRow{}
	for rows.Next() {
		var i ReadEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Text,
			&i.Details,
			&i.Omitted,
			&i.At,
			&i.HasFullText,
			&i.OmissionReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readSelectedEvents = `-- name: ReadSelectedEvents :many
SELECT id, kind, text, details, omitted, created_at, EXISTS(SELECT 1 FROM core.conversation_message_bodies b WHERE b.event_id=conversation_events.id) AS has_full_text, omission_reason
FROM core.conversation_events WHERE owner=$1 AND id=ANY($2::bigint[]) ORDER BY id
`

type ReadSelectedEventsParams struct {
	Owner   string
	Column2 []int64
}

type ReadSelectedEventsRow struct {
	ID             int64
	Kind           string
	Text           string
	Details        json.RawMessage
	Omitted        bool
	At             time.Time
	HasFullText    bool
	OmissionReason string
}

func (q *Queries) ReadSelectedEvents(ctx context.Context, arg ReadSelectedEventsParams) ([]ReadSelectedEventsRow, error) {
	rows, err := q.db.Query(ctx, readSelectedEvents, arg.Owner, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadSelectedEventsRow{}
	for rows.Next() {
		var i ReadSelectedEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Text,
			&i.Details,
			&i.Omitted,
			&i.At,
			&i.HasFullText,
			&i.OmissionReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readSummary = `-- name: ReadSummary :one
SELECT version, through_id, text FROM core.conversation_summaries WHERE owner = $1
`

type ReadSummaryRow struct {
	Version   int64
	ThroughID int64
	Text      string
}

func (q *Queries) ReadSummary(ctx context.Context, owner string) (ReadSummaryRow, error) {
	row := q.db.QueryRow(ctx, readSummary, owner)
	var i ReadSummaryRow
	err := row.Scan(&i.Version, &i.ThroughID, &i.Text)
	return i, err
}

const readText = `-- name: ReadText :one
SELECT e.id, e.omitted,
 CASE WHEN e.omitted THEN '' ELSE substring(COALESCE(b.body,e.text) FROM $1::integer+1 FOR $2::integer) END::text AS text,
 CASE WHEN e.omitted THEN '' ELSE COALESCE(b.body_sha256,encode(sha256(convert_to(e.text,'UTF8')),'hex')) END::text AS digest,
 CASE WHEN e.omitted THEN 0 ELSE COALESCE(b.character_count,char_length(e.text)) END::integer AS total,
 COALESCE((SELECT generation FROM core.conversation_history_generations WHERE owner=e.owner),0)::bigint AS generation
FROM core.conversation_events e LEFT JOIN core.conversation_message_bodies b ON b.event_id=e.id
WHERE e.owner=$3 AND e.id=$4
`

type ReadTextParams struct {
	CharacterOffset int32
	CharacterLimit  int32
	Owner           string
	EventID         int64
}

type ReadTextRow struct {
	ID         int64
	Omitted    bool
	Text       string
	Digest     string
	Total      int32
	Generation int64
}

func (q *Queries) ReadText(ctx context.Context, arg ReadTextParams) (ReadTextRow, error) {
	row := q.db.QueryRow(ctx, readText,
		arg.CharacterOffset,
		arg.CharacterLimit,
		arg.Owner,
		arg.EventID,
	)
	var i ReadTextRow
	err := row.Scan(
		&i.ID,
		&i.Omitted,
		&i.Text,
		&i.Digest,
		&i.Total,
		&i.Generation,
	)
	return i, err
}

const recentEvents = `-- name: RecentEvents :many
SELECT id, kind, text, details, omitted, created_at, has_full_text, omission_reason FROM (
  SELECT id, kind, text, details, omitted, created_at, EXISTS(SELECT 1 FROM core.conversation_message_bodies b WHERE b.event_id=conversation_events.id) AS has_full_text, omission_reason
  FROM core.conversation_events WHERE owner = $1
  ORDER BY id DESC LIMIT $2::bigint
) recent ORDER BY id
`

type RecentEventsParams struct {
	Owner       string
	RecentLimit int64
}

type RecentEventsRow struct {
	ID             int64
	Kind           string
	Text           string
	Details        json.RawMessage
	Omitted        bool
	At             time.Time
	HasFullText    bool
	OmissionReason string
}

func (q *Queries) RecentEvents(ctx context.Context, arg RecentEventsParams) ([]RecentEventsRow, error) {
	rows, err := q.db.Query(ctx, recentEvents, arg.Owner, arg.RecentLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecentEventsRow{}
	for rows.Next() {
		var i RecentEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Text,
			&i.Details,
			&i.Omitted,
			&i.At,
			&i.HasFullText,
			&i.OmissionReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summaryEvents = `-- name: SummaryEvents :many
SELECT id, kind, text, details, omitted, created_at, EXISTS(SELECT 1 FROM core.conversation_message_bodies b WHERE b.event_id=conversation_events.id) AS has_full_text, omission_reason
FROM core.conversation_events
WHERE owner = $1 AND id < $2 AND summarized_version = 0
 AND NOT EXISTS(SELECT 1 FROM core.conversation_message_bodies b WHERE b.event_id=conversation_events.id)
ORDER BY id LIMIT $3::bigint
`

type SummaryEventsParams struct {
	Owner     string
	BeforeID  int64
	PageLimit int64
}

type SummaryEventsRow struct {
	ID             int64
	Kind           string
	Text           string
	Details        json.RawMessage
	Omitted        bool
	At             time.Time
	HasFullText    bool
	OmissionReason string
}

func (q *Queries) SummaryEvents(ctx context.Context, arg SummaryEventsParams) ([]SummaryEventsRow, error) {
	rows, err := q.db.Query(ctx, summaryEvents, arg.Owner, arg.BeforeID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SummaryEventsRow{}
	for rows.Next() {
		var i SummaryEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Text,
			&i.Details,
			&i.Omitted,
			&i.At,
			&i.HasFullText,
			&i.OmissionReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
